### ISSUE TITLE
AOK: highlight "most representative" ephys source on Evidence page

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#186]
Before the user opens any of the citation sources, there should be an indication as to which source contains the "most representative" value being presented in the ephys summary table.  Perhaps the "most representative" source could simply be listed first.

**Comment by drdiek** [comment]
Is there a way to highlight the "most preferred" source before the user opens all of the citations?  Should this be a separate ticket?

**Comment by ChristopherRees** [comment]
Technically, we don't have a "most preferred" source.  A single source might have one piece of evidence reported under preferred conditions and one that's not.  There might also be several sources that contain at least one piece of evidence from preferred conditions.  So the evidence itself is at the correct level; not the source.

That said, if we do want to show something to users before they open the evidence, it's possible (e.g. A outline/fill color for the table that indicates the source contains at least one preferred piece of evidence) .  I would make this a separate ticket.
