### ISSUE TITLE
DWW: There is a problem displaying all of the necessary figures on the markers Evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#201]
We have a major problem with the marker figures displaying correctly.  The problem arises when we have a single figure that displays multiple markers for a single cell type with a single Reference ID pointing to the figure.  I have made separate copies of a given figure in order to highlight the multiple markers of interest.  For example say a figure of a CA1 Basket cell displays the expression for PV, CCK, and CB.  I would have made three copies of the figure, each time highlighting the different markers.  Right now the database is not able to resolve these three figures from each other.  The portal simply displays the first one that is listed in the database.

**Comment by dhamilt5** [comment]
This may require expanding the marker Reference IDs, like we did for ephys, to account for the uniqueness of evidence-property-type specific evidences as they relate to select figures.

**Comment by dhamilt5** [comment]
On second thought, I believe we can simply add a "Parameter" column to "attachment_marker.xlsx". This is how we resolve figures/tables to evidence/property/type for ephys, and it should work just as well for markers, too.
