### ISSUE TITLE
DWW: clicking on a marker column header returns too many listed cell types

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#208]
When clicking on the column header CR, 142 cell types are returned.  Some cell types with mixed expression are getting listed 3 times: once under positive expression, once under negative expression, and once under mixed expression.  They should only be listed once under mixed expression, when the expression is in fact mixed.

**Comment by dhamilt5** [comment]
From: David Hamilton
Date: Wed 5/20/2015 10:04 AM
This marker column header click behavior, as Diek describes it [above], is the original behavior when implemented a while ago. It was per the original requirements as we understood them to be at the time of implementation. Do we really want to change the requirements for this capability? My thinking is that we may not. Isn't it more desirable to list all expressing types under each category? Please let me know if we really do want to change this behavior.

**Comment by dhamilt5** [comment]
The question was answered. The initial comment by Diek accurately describes the newly revised requirements and desired functionality for this capability.

**Comment by dhamilt5** [comment]
From: Diek W Wheeler <dwheele5@gmu.edu>
Sent: Tuesday, November 17, 2015 2:41 PM
I was just checking on issue #208 to see if it were ready for Production or not. When I click on CR, 126 cell types are listed. I managed to find LIII Pyramidal listed once under negative expression and once under unknown expression. The same negative‐unknown confusion appears for LII‐III Pyramidal‐Tripolar, MEC LII Stellate, and LI‐II Pyramidal‐ Fan. All four of these are EC cell types. I think I understand why there might sometimes be less than 122 cell types listed, but the number should never exceed 122.
