### ISSUE TITLE
DWW: incorrect linking quote is appearing

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#209]
When I clicked on CR expression is Granule cells, the same linking quote appears for all but one of the different citations.  This should not be possible, since each article should have a unique version of the linking quote, unless it is the statement "All necessary morphological evidence is present in this self-same publication."

**Comment by dhamilt5** [comment]
The cause of this issue may be the latest "URD_marker_201505041816.csv". If there is a problem with the linking quotes on the website, this csv file is likely to blame. To fix the problem (if one exists), we most likely must ingest a new version of this cvs.

**Comment by dhamilt5** [comment]
From: Charise White
Date: Wed 5/20/2015 9:25 AM
The linking quote "Principal neurons identified by the presence of their somata in the principal cell layer, which is densely packed with and nearly homogeneous for the somata of the subregion's principal neurons (Czeh et al., 2013, Acta Biologica Hungarica)" is generic.  It is what I use for data from the principal cell layers; therefore, the portal is correct.
