### ISSUE TITLE
DWW: modify search to accommodate new lower limit maxFR values

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#212]

**Comment by dhamilt5** [comment]
From: David Hamilton
Date: Fri 6/5/2015 7:36 AM
To: Diek W Wheeler <dwheele5@gmu.edu>
Subject: Issue 212 - Modify search to accommodate new lower limit maxFR values
Hi Diek,
Please clarify what this issue is. It appears to me that this functionality already exists.
Thanks,
David

**Comment by dhamilt5** [comment]
From: Christopher Rees
Date: Fri 6/5/2015 9:37 AM
Subject: Issue 212 ‐ Modify search to accommodate new lower limit maxFR values
Hi David,
Yes, the way we added the GT column to the database means the search should still work correctly. Christopher
