### ISSUE TITLE
CLR: some ephys pg locations and protocols are missing

### ISSUE THREAD

**Issue by ChristopherRees** [Hippocampome-Org/php#214]
After Alexander's latest ephys spreadsheet update (2015-05-29), the pg locations and protocols are missing from the new evidence.

See Max FR greater-than values.  Also see the CA1 C-R neuron type.  (Possibly others?)

**Comment by dhamilt5** [comment]
The ephys URD and attachments must be updated with data matching the latest ephys data entries to fix this issue.

**Comment by drdiek** [comment]
The URD_ephys and attachment_ephys files have been updated in the Database folder, as has the attachments folder.

**Comment by drdiek** [comment]
All of the new entries have now been completed and are ready for import.
