### ISSUE TITLE
CLR: Clicking on a marker column header - fixing mixed flags with overriding calls

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#251]
Currently a mixed flag result is listed under the “Types with mixed expression” section with parenthetical statements saying either “positive” or “negative.” For example, if one clicks on CR from the marker matrix, there is listed the following:

Types with mixed expression
CA3c (e)03223p (000S0) Pyramidal (negative).

Instead of being listed under “Types with mixed expression,” it should be listed under the “Types with negative expression” section, with the parenthetical statement “contradictory evidence exists” added to the end

Types with negative expression
CA3c (e)03223p (000S0) Pyramidal (contradictory evidence exists).

To make this work properly, the overriding calls in curly braces from the main marker spreadsheet must be correctly interpreted from the database.

**Comment by dhamilt5** [comment]
From: Diek W Wheeler <dwheele5@gmu.edu>
Sent: Tuesday, November 17, 2015 2:41 PM
I was just checking on issue #208 to see if it were ready for Production or not. When I click on CR, 126 cell types are listed. I managed to find LIII Pyramidal listed once under negative expression and once under unknown expression. The same negative-unknown confusion appears for LII-III Pyramidal-Tripolar, MEC LII Stellate, and LI-II Pyramidal-Fan. All four of these are EC cell types. I think I understand why there might sometimes be less than 122 cell types listed, but the number should never exceed 122.

**Comment by dhamilt5** [comment]
There is still a problem...

Clicking on the following marker column headers (at least, and maybe several others) results in a warning (see below) - ∝-act2, AChE, AMPAR2/3, CB1, GABAa ∝1, Mus2R, NG,RLN, SubPRec

Warning: array_intersect() [function.array-intersect]: Argument #1 is not an array in /home/hippocam/public_html/csv2db/neuron_by_marker.php on line 122
No mixed Type found

Also, why is the font color (i.e. black) of the "Types with mixed expression" different than the font color (i.e. blue) of all the other types listed?
