### ISSUE TITLE
DJH: incorporate latest version of jqGrid to fix lag in rendering full marker matrix

### ISSUE THREAD

**Issue by dhamilt5** [Hippocampome-Org/php#253]
The current version of jqGrid used by Hippocampome.org is 4.6 (as of 27-Nov-2015). The latest available version of jqGrid (as of 19-Oct-2015, per http://www.trirand.com/blog) is 5.0.1. Incorporating the latest version of jqGrid will likely fix the lag in rendering the full marker matrix problem.

From: Charise M White cwhite14@gmu.edu
Sent: Friday, November 27, 2015 1:11 AM
...can anything be done about the delay in displaying the full marker matrix?  If not, perhaps the check marker could appear in the box immediately to inform the user that the request was submitted.  I found myself clicking the box a few times thinking that my request had not been received.

**Comment by dhamilt5** [comment]
We are deferring this fix until jqGrid 5.x.x becomes stable.

**Comment by drdiek** [comment]
latest jqGrid 4.4 doesn’t gives us any improvement on marker page, further it is not working for electrophysiology matrix and later version above 4.2 are paid - Amar
