### ISSUE TITLE
AOK: [FP] "Author original FP descriptions" should be searchable

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#296]
In the same way that Neuron Names/Synonyms are searchable, "Author original FP descriptions" should be searchable and return the corresponding Hippocampome.org Firing Pattern type.

For example, "interrupted fast-spiking discharge pattern" should return "PSTUT" for Hippocampome.org cell type 4036, which is CA1 (i)2232 Axo-axonic.

**Comment by gas10** [comment]
Hi Diek,
            I am not sure about how you want the design of this page, Also where to add link for Author original FP descriptions, so I added it in search option 'Original Firing Pattern'. I removed the letter(First Column in search) as there are very few FP name description in select dropdown. Also I put the Firing Pattern as first column keeping same result column as that of Neuron Name/Synonym search. Please provide your feedback whether I am following right design approach as you mentioned in comments above?

Thanks & Regards,
Amar Gawade
<img width="1227" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/3513676/20199055/1b30fdba-a776-11e6-952b-f166da4b3da1.png">
<img width="1215" alt="screen shot 20" src="https://cloud.githubusercontent.com/assets/3513676/20199056/1b368c26-a776-11e6-82e9-8632d52c6e1e.png">

**Comment by drdiek** [comment]
Amar,

This looks good. I look forward to the chance to play around with it once it is on csv2db.

Sincerely,
Diek
