### ISSUE TITLE
AOK: [ephys] One of the ephys figures is not displaying as it should

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#300]
I have taken a look at the URD and attachment files and the figure file itself. As far as I can tell, the figure should be displaying, but it is not.
![screen shot 2016-10-24 at 7 37 33 pm](https://cloud.githubusercontent.com/assets/4380011/19693984/9d812ae2-9aab-11e6-913d-211597d28e84.png)
![screen shot 2016-10-24 at 7 36 45 pm](https://cloud.githubusercontent.com/assets/4380011/19693993/a2903cbc-9aab-11e6-89c0-3833ebf23110.png)

**Comment by gas10** [comment]
Hi Diek,
           I think attachment associated with this evidence is not found in
attachment folder. The image name is
'attachment/ephys/Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell6086-Vthresh.jpeg'.
Are you sure this image is there in attachment/ephys folder?

Thanks & Regards,
Amar Gawade

**Comment by drdiek** [comment]
Amar,
I am puzzled. The file definitely exists in the Database/attachment_ephys folder, so it should have been read imported onto the Hippocampome.org server. I will contact David about this.
Sincerely,
Diek

**Comment by dhamilt5** [comment]
attachment/ephys filename
Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell8086-Vthresh.jpeg

attachment_ephys.csv "Name of file containing figure"
Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell6086-Vthresh.jpeg

**Comment by drdiek** [comment]
I have renamed the following 4 files in the Database/attachment_ephys folder:

Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell6086-APampl.jpeg
Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell6086-fAHP.jpeg
Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell6086-sAHP.jpeg
Gloveli-Heinemann-2001-413-EurJNeurosci-Fig4Bbcd-Cell6086-Vthresh.jpeg

These need to be propagated through to Prod.
