### ISSUE TITLE
DWW: [ephys error] There is a figure missing from one of the ephys evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#307]
When one clicks on maxFR for CA1 Basket CCK+ (Ref ID 4079), under the citation for Cope et al., the figure is not appearing. The link name, the file name, and the attachment_ephys entry are all the same. Is there a php reason for this figure not appearing?

**Comment by gas10** [comment]
Hi Diek,
            I checked this and it is not a php issue. The name of the image that is stored in database attachment table is 'Cope-Maccaferri-2002-Neuroscience-Fig4B1-Cell4079-maxFR.jpeg'. I think either this image name in database is incorrect or It is not there in attachment folder that contains all images. 

Thanks & Regards,
Amar Gawade

<img width="1206" alt="screen shot 2016-12-24 at 7 23 38 pm" src="https://cloud.githubusercontent.com/assets/3513676/21469253/959d7cd0-ca0e-11e6-809c-eb9c496a6109.png">

**Comment by drdiek** [comment]
David,

I have checked the Database and the entry seems to be fine. Could you please check to see if the figure actually exists in the ephys attachment folder?

Sincerely,

Diek
