### ISSUE TITLE
GAA: [markers] the 6800 markers extracted from the ABA need to be added to the principal cell markers pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#311]
GAA left it open as to whether the listings are live updated from the ABA website or are simple static PDF listings.

**Comment by gas10** [comment]
Hi Diek,
            I don't understand what exactly need to be done in this issue. Can you please elaborate further like which spreadsheet contains data for marker that is specified in issue? what is 6800? On which page this data should be displayed? 
Thanks,
Amar
