### ISSUE TITLE
GAA: netlist csv file does not download correctly from connectivity page

### ISSUE THREAD

**Issue by ChristopherRees** [Hippocampome-Org/php#326]
Ask David or Christopher for the chain of emails from Giorgio on 20170420.

The netlist file does not seem to download correctly on all browser/os combos.  Problem reported on IE11/Windows 7.  Mixed results on Chrome/OSX and Safari/OSX.  Possible issue with Excel icon being displayed.  Possible fix:  use simple text link to file.

No issues reported with link to this file from the help page.

**Comment by drdiek** [comment]
comment from David:  browser not supported
