### ISSUE TITLE
K1M: [search] Show more info in search engine results

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#342]
1. I would like to have a checkbox to hide/show the complete morphology of presynaptic and postsynaptic neurons.
2.  Please change the title of the "SID" column to "Presynaptic ID", and "DID" column to "Postsynaptic ID".

**Comment by drdiek** [comment]
For point #1, does this mean you would like to only see the ID columns and hide either of the "Presynaptic Cell Types" and/or "Postsynaptic Cell Types" columns?

**Comment by k1moradi** [comment]
No. By morphology, I mean the numeral names that shows the presence or absence of dendrites and axons in different layers. We can do that by adding two new columns. Like what we have on the biomarkers tab, but it would have been nice to have the complete morphology with all the projections. Anyways, the functionality seems to be there in the markers tab and needs to be ported to search engine tab too.

**Comment by drdiek** [comment]
I can implement a solution to problem 1, whereby I simply list the full name of the neurons, such as DG(1)2232 Basket or CA3c (e)03223p-DG_0101-CA2_0101-CA1_0101-SUB_100 Pyramidal. Would this satisfy the request, or does the information have to be on a toggle?

**Comment by k1moradi** [comment]
I think having the full name will be a good short-term or long-term solution that I can use. It is not a big deal, but is it possible to change the name order to CA3c Pyramidal (e)03223p-DG_0101-CA2_0101-CA1_0101-SUB_100 for example? The reason I am asking this name format is that the result table of search engine is sortable. I mean if one clicks on the title the sorting will change.
