### ISSUE TITLE
AOK [FP]: display new protocol information including solutions on FP evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#347]
The M&M spreadsheet contains 4 parts: Animals, Preparations,  Artificial cerebrospinal fluid and Recording method/Pipette solutions.

The data could be presented on Firing Pattern Evidence page  similar to FP parameters.

Each group of data could appear in tabulated format after clicking "Show all animal data", "Show all preparation data", "Show all ACSF data", "Show all recording method data". - Alexander

**Comment by gas10** [comment]
Fixing issue #363 will fix this issue.
