### ISSUE TITLE
K1M [Search Engine] Include:() function does not work for presynaptic connection.

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#352]
Include:() function do not work for presynaptic connection. For example , in the following search query it do not work.

Connection:(Presynaptic:(Morphology:((Dendrites:DG:1111 AND Axons:DG:0???) AND (Soma:DG:??1? OR Soma:DG:???1)) AND electrophysiology:Max_Fr:>50 AND Neurotransmitter:Inhibitory, Include:(1009)), Postsynaptic:(Morphology:Soma:DG:??1? AND Neurotransmitter:Excitatory))

but if we put the include for the postsynaptic neuron it will work:

Connection:(Presynaptic:(Morphology:((Dendrites:DG:1111 AND Axons:DG:0???) AND (Soma:DG:??1? OR Soma:DG:???1)) AND electrophysiology:Max_Fr:>50 AND Neurotransmitter:Inhibitory), Postsynaptic:(Morphology:Soma:DG:??1? AND Neurotransmitter:Excitatory, Include:(1009)))

**Comment by gas10** [comment]
Hi Kevin,
             There is no neuron connection for presynaptic neuron with id
1009. It is giving result for second query because in this case it act as a
post synaptic neuron. If you want result set to include both ways
connection then ask jhanvi to modify the query( including 1035-->1009 as
well as1009-->1035).

Condn: 1035(pre)---->1009(post)
hence 1009 can't be considered presynaptic. Current logic doesn't check for
vice versa.

Thanks & Regards,
Amar Gawade

**Comment by k1moradi** [comment]
Hi Amar,

I did not know you check this git :). Nice to see you here again.

We designed the Include and Exclude to act in God mode with the power of including a neuron type to the list of pre or postsynaptic cells. Then the results should be displayed if any potential connection exist for that type.

Here for example, 1009 (DG HICAP) connects to 1000 (DG Granule). This connection is both a potential connection and an approved connection.

You can check the existence of this connection on the website.
http://hippocampome.org/csv2db/property_page_connectivity.php?id1_neuron=1009&val1_property=DG_SMi&color1=violet&id2_neuron=1000&val2_property=DG_SMi&color2=blue&connection_type=1&known_conn_flag=1&axonic_basket_flag=0&page=1

I am not sure what I am missing?

Best,
Keivan

**Comment by gas10** [comment]
Hi Kevin,
              🤔 I think this might be a bug then 😞

Thanks & Regards,
Amar Gawade
