### ISSUE TITLE
K1M: [search] Search Engine and API: The neurotransmitter should accept OR operator

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#356]
The neurotransmitter should accept OR operator.
For example, the following search query only shows excitatory presynaptic neurons while both excitatory and inhibitory presynaptic neurons is requested.

```
Connection:(Presynaptic:(Neurotransmitter:(Excitatory OR Inhibitory)), Postsynaptic:(Morphology:(Dendrites:DG:1000 AND Axons:DG:1000 AND (Axons:CA1:?000 OR Axons:SUB:?00))))
```

**Comment by gas10** [comment]
@k1moradi You can simply type both instead of Excitatory OR Inhibitory. Please refer below mentioned query.

Connection:(Presynaptic:(Neurotransmitter:Both), Postsynaptic:(Morphology:(Dendrites:DG:1000 AND Axons:DG:1000 AND (Axons:CA1:?000 OR Axons:SUB:?00))))

**Comment by k1moradi** [comment]
Thanks, Amar! so I think it is not necessary to fix this issue.
