### ISSUE TITLE
DWW: [Izhikevich] On the Neuron Pages under the section on Izhikevich parameters the FitFiles do not download properly

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#382]

**Comment by drdiek** [comment]
When I click on a FitFile link, the address shown ends with fitfile_.json. There is some detail missing in the file name, so the downloads are not working.

**Comment by Nikhilkoneru** [comment]
Hi Diek,

     Updated, you can now download fit-files.
