### ISSUE TITLE
K1M:[ePhys]: v1.0 CA1 Horizontal Axo-Axonic Rin and tau might be wrong

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#416]
The extracted values are not what is shown in the reference table.
I think the proper values should be the following. You can find the reference 2901146 under the CE tab of my google sheet.
217±34 (n=4)@2901146{CA1 Horizontal Axo-axonic} 
23±7(n=4)@2901146{CA1 Horizontal Axo-axonic}

**Comment by drdiek** [comment]
According to Alexander's spreadsheet, he took the average of the highest (252) and the lowest (186) numbers, instead of averaging all 4 numbers in the table, to achieve a mean of 219 for RIn. I do not understand why the error is reported as ±219.

**Comment by k1moradi** [comment]
Diek,

This is a systematic error in the hippocampome.org. I think whenever the portal is unable to find the measure of spread it uses measure of central tendency instead. I am not sure how accurate or correct is this method.

Best,
Keivan

**Comment by drdiek** [comment]
Alexander:
"In the literature there are many ways to present electrophysiological parameters. The paper if Ganter et al. (2004) contains a table with four values of input resistance of Horizontal AA cells (MOhm): 186, 189, 240, 252. In this and other similar cases, we did not perform statistical processing of original literary data, but indicated only their ranges. In this form they are presented both in my MS Excel spreadsheet (15098728 {Tab1; [186,252]}) and in the eLife article ( [186,252]). In the table on the portal, the data are presented in a simpler form, either of average values (if they were given in the literature) or of the middle of the ranges (219 in case of Rin of Horizontal AA cell). If the mean and standard deviation (SD) or standard error of the mean (SEM) were included in the electrophysiological paper, then the eLife article would indicate data in the form of the mean+-SD (217+-30 (4) ), and the mean would be presented in the table on the portal (217).

However, the portal evidence page contains an error. It says 219+-219 (n=2), which does not make sense. I think it should be [186,252]."
