### ISSUE TITLE
K1M: [ePhys]: Wrong values are extracted from PMID 20421280 for v1.0 Rin and tau

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#417]
The values' format is median [2nd IQR to 3rd IQR]. Right now the reported format is using ± with a wrong measure of spread.

Also for CA1 Pyramidal cell, the reported Rin median is 101, not 111.

**Comment by drdiek** [comment]
For CA1 Pyramidal, the reported value by the authors for Rin is 101 (91-131) (n=19). Once again, it would appear that Alexander has averaged the highest and lowest values to find his reported value. I assume he is doing this to keep things consistent. Again, I do not understand the error value.

**Comment by k1moradi** [comment]
I think the proper way of calculating the measure of spread in cases we have IQR is to use IQR75% - IQR25% in front of +- sign.

**Comment by drdiek** [comment]
I have forwarded parts of this conversation and the one about CA1 Horizontal Axo-axonic cells to Alexander to see if he has any comments about what is going on with the reporting.

**Comment by k1moradi** [comment]
Rin of SUB Pyramidal is also has a wrong measure of spread. The reference is missing also.
The RefID is 500102027510103.

**Comment by drdiek** [comment]
Alexander:
"In the literature there are many ways to present electrophysiological parameters. The paper if Ganter et al. (2004) contains a table with four values of input resistance of Horizontal AA cells (MOhm): 186, 189, 240, 252. In this and other similar cases, we did not perform statistical processing of original literary data, but indicated only their ranges. In this form they are presented both in my MS Excel spreadsheet (15098728 {Tab1; [186,252]}) and in the eLife article ( [186,252]). In the table on the portal, the data are presented in a simpler form, either of average values (if they were given in the literature) or of the middle of the ranges (219 in case of Rin of Horizontal AA cell). If the mean and standard deviation (SD) or standard error of the mean (SEM) were included in the electrophysiological paper, then the eLife article would indicate data in the form of the mean+-SD (217+-30 (4) ), and the mean would be presented in the table on the portal (217).

However, the portal evidence page contains an error. It says 219+-219 (n=2), which does not make sense. I think it should be [186,252]."
