### ISSUE TITLE
NK: [search] Syntax highlighter is not working properly

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#443]
The highlighter code appears to be messing with greater than (>) and other related characters in search strings.

**Comment by k1moradi** [comment]
I tested this search string > sign works for me locally.

Connection:(Presynaptic:(Neurotransmitter:Excitatory AND Morphology:(Axons:CA1:?1?? OR Soma:CA1:?1??)), Postsynaptic:(Morphology:(Soma:CA1:?1?? AND Dendrites:CA1:?100) AND Electrophysiology:Rin:>100))

Could you please provide an example?

PS: I also noticed the syntax highlighter is disabled on the CSV2DB and production site.

**Comment by drdiek** [comment]
That is very interesting that it work on your machine. Something is obviously different in your local files from what is on GitHub and on the 4 web sites. I think we need to get a copy of your local files, at least the search-related ones, to Nikhil, for analysis.

The syntax highlighter has been temporarily disabled because it was causing all 4 web sites to glitch when processing > signs and such.

**Comment by drdiek** [comment]
A new script has been written that sits on the cng.gmu.edu server in the /var/www/html/dbbackups directory, which backs up the four databases every month and deletes files after six months. The backups reside in a sub-folder within the same directory.
