### ISSUE TITLE
KM: [General] SSL support

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#452]
Google Chrome, which has a 70% market share, is going to block access to unencrypted web traffic in the future release. I have noticed that hippocampome.org is not working properly when HTTP is replaced with HTTPS. I think we need to fix this problem ASAP before people lose their access.

**Comment by drdiek** [comment]
![1496175145_http-flowchart](https://user-images.githubusercontent.com/4380011/66326366-d387c500-e8f6-11e9-8ac0-689621c4be3e.jpg)
