### ISSUE TITLE
KM: [Advanced Search]: The explanation are missing.

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#453]
We had a set of comments and links under the advanced search section of the hippocampome.org. However, on the PHP site, this information is missing.
![image](https://user-images.githubusercontent.com/18602635/66273664-cc53af00-e843-11e9-83e4-5ab7ee26249d.png)

**Comment by drdiek** [comment]
The problem is that Nikhil's local version, from which he has been making changes, does not have the associated comments. I have now updated all of the sites and sent Nikhil a copy of the latest code with the needed comments included.
