### ISSUE TITLE
CT: [neurites] Enable the downloading of a connectivity netlist with associated synaptic probabilities

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#469]

**Comment by nmsutton** [comment]
@drdiek I have completed this task. I have added custom netlists and other downloads for the NxK and NxM matrices. A note about this is that there is now a synap_prob/data directory on the server that I placed in the .gitignore file list. The downloadable files will be ones the server but users do not download them every time they clone the git repo. Please check the work by inspecting the new content on the right side of each matrix page and if it looks fine, please close this issue.

**Comment by drdiek** [comment]
@nmsutton I think the downloads need some tweaking before I sign off on them. First, I think we can remove completely the CSV Data Page and the CSV Neurite Page. I think what we need is sort of a hybrid of the Netlist and the XLSX Matrix Data. I like the Netlist, but I would add one more column that can be found in the XSLSX Matrix Data: the values from the 'Total_length (μm)' column. For the Somatic Distances of Dendrites and Axons matrix I would add the 'Mean_path_length (μm)' column values to the Netlist. I would make similar modifications to the NxN matrices, although I notice that you are linking an outdated version of the XLSX Matrix Data (see attached), because it does not have all of the necessary data columns: Potential synapses, Number of contacts, and Probability.
[Potential Synapses 4.0.xlsx](https://github.com/Hippocampome-Org/php/files/4134614/Potential.Synapses.4.0.xlsx)

**Comment by nmsutton** [comment]
@drdiek Ok, sounds good. Since it is a hybrid, I am guessing it is better to just name it total_length.csv, etc., rather than netlist.csv. I am guessing also you mean I should include the average mean total length values rather than every non-averaged value. I can also include columns for values found in the matrix, e.g., value count and standard deviation. Does that sound acceptable?

**Comment by drdiek** [comment]
@nmsutton Yes, use the average values and please do include the value counts and standard deviations.

**Comment by nmsutton** [comment]
@drdiek I have now updated the files and pages to include custom csv files for each of the 5 pages. Each csv file contains neuron/neurite or pre/post pairs, average value, standard deviation, and value count. I also uploaded and linked to the Potential Synapses 4.0.xlsx file you provided on the site. Please review the work and if this is acceptable please close this issue. I left also the netlist files for now, and named the files with values separately. Should the original style netlist files be removed or should they be left there with the other files?

Also, btw, I converted all synap. prob. figure images to having white backgrounds now too.

**Comment by drdiek** [comment]
@nmsutton It is looking good.

I would leave the netlists and associated csv files, but I would remove the xlsx files, as I feel they would just be confusing to the typical user who downloaded them.

Also, as a small personal matter, when it comes to providing a value for counts, I would prefer to see an integer, rather than a floating-point number with two decimal places.

**Comment by nmsutton** [comment]
@drdiek Thanks and I appreciate you looking it over. I have now removed the xlsx files. I have also regenerated the csv files to all have integers in their counts columns.
