### ISSUE TITLE
CT: [neurites] Revamp the axonal-dendritic lengths Evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#479]
1) Change the title from "Synapse probabilities evidence page" to "Synapse Probabilities - Dendritic/Axonal Lengths Evidence page"
2) Modify the "axon_dendrite_somata" phrase in the Neuron Type section to be either "axon" or "dendrite" as appropriate
3) Remove one of the axon and dendrite check boxes as appropriate, but do not list them both
4) After the Page location listing, add a "Dendritic length" or "Axonal length" as appropriate along with the appropriate neurite
5) Add "Figure segmentation evidence" for the appropriate neurite
6) Add a clickable icon that leads to the appropriate PNG figure file (download_PNG.png icon soon to be available in images/ folder on the server)
7) Instead of displaying the separate pictures for axons and dendrites for each parcel, display only the original whole image

![A D lengths Evidence page](https://user-images.githubusercontent.com/4380011/75187789-d1dd6300-5718-11ea-8c4d-2921ce655d7e.jpg)

**Comment by drdiek** [comment]
@nmsutton please hold off on this Issue while I accommodate Giorgio's latest feedback on the display layout.

**Comment by drdiek** [comment]
@nmsutton this Issue is now ready to be addressed.

**Comment by nmsutton** [comment]
@drdiek I was working on this and in your screenshot in the [4] area it appears for each evidence entry the dendritic length is listed. Would it be better to put the length statistics before evidence listing, as shown in the screenshot below, to not have it repeated in each evidence entry? Also in  [4], would it be helpful to include "of axons" or "of dendrites" in addition to the parcel when listing the statistic? Would it be helpful to include mean, std, count, min, max as in the screenshot also?
![evi_page](https://user-images.githubusercontent.com/3514598/75376698-75a44b80-589e-11ea-8179-c6cd9d099401.png)

**Comment by drdiek** [comment]
@nmsutton no, we should not put the length statistics above all of the evidence listings. Each article, in fact, each figure in each article will have its length value listed. Therefore, there is likely only one value to be reported, so the mean, standard deviation, max, and min have no meaning here.

You seem to be a little confused about the nature of the lengths Evidence pages. Each page will describe either the axons or the dendrites, but not both on the same Evidence page. Therefore my comment about [3]. Perhaps to ease this confusion, [1] should display "Dendritic" or "Axonal," rather than the combination of "Dendritic/Axonal."

In [4], you need to use the phrase "Dendritic lengths" or "Axonal lengths" depending on which type of neurite is being described. Therefore, it will be unnecessary to include the phrases "of axons" or "of dendrites."

**Comment by nmsutton** [comment]
@drdiek thanks Diek, now I see the difference you are talking about. To get that statistic value for each fragment entry I will probably need to convert fragment_id -> evidence_id, then evidence_id -> [neuron_id, neurite_id], then fragment_id -> original_reference_id, then use [neuron_id, neurite_id,  original_reference_id] triplets for calculating the neurite_quantified statistics using Mysql specifically for each of the fragments listed. That may be a bit complex but I will work on it and hopefully it will go smoothly.

Yes, I made that basic mistake of not reading the “Dendrite length” description close enough to realize that will not pertain to axons, my apologies and thanks for the correction. I will make sure to write [1] differently as you recommend.

**Comment by drdiek** [comment]
@nmsutton I am sorry it is so complicated to retrieve the necessary information. I agree with your proposed method of retrieval.

**Comment by nmsutton** [comment]
@drdiek I have done the work listed here. Thanks for the detailed screenshot and list of tasks, that really helps me with the work! It turns out getting the triplet mentioned for the statistic was fairly straightforward. One note is that in [3] I removed the neurite checkbox because in the current version of the pages the type of neurite is mentioned twice before that (in [1] and [2]) and some after that (e.g., [5]) so it seems it could potentially be redundant. If it is wanted for it to be put back in please tell me and it would be easy to do that. In [5] I put the neurite abbreviation last, instead of first in the screenshot, because that is how it is coded in the database, but please tell me if the orger should be changed as shown in the screenshot. Please review the work and if it looks acceptable please close this issue.

**Comment by drdiek** [comment]
@nmsutton thank you for correcting the ordering.
