### ISSUE TITLE
CT: [neurites] Revamp the Number of Potential Synapses / Number of Contacts / Synaptic Probabilities Evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#482]
Change the title from "Synapse probabilities evidence page" to "Synapse Probabilities - Parcel-Specific Potential Synapses Per Neuron Pair"
1) The titles of the tables should be in blue and emboldened
2) The parcel labels of the tables should be the same blue as the table titles
3) All of the fonts associated with the tables should be reduced to match the size of the fonts on the rest of the page
4) Remove all of the buttons and selectors and messages associated with the bibliography section as these pages will not have any bibliographic information associated with them
5) The Number of Contacts table should list values with only 2 decimal places only
6) The values in the tables should be linked to the appropriate new n-by-n Evidence pages

**Comment by nmsutton** [comment]
@drdiek I have tried to create this updated page ([example link](http://www.hippocampome.org/phpdev/property_page_synpro_pvals.php?id_neuron_source=1002&id_neuron_target=1002&color=violetSoma&page=1&nm_page=ps)). Please take a look and tell me what you think.

**Comment by drdiek** [comment]
@nmsutton it looks very good.

**Comment by nmsutton** [comment]
@drdiek good to hear that. The functionality requested has been added from what I understand, and if this looks completed please close this issue.
