### ISSUE TITLE
CT: [neurites] Add .rar spreadsheet to the database ingest scripts

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#483]
[attachment_neurite_rar_v1.0.xlsx](https://github.com/Hippocampome-Org/php/files/4227183/attachment_neurite_rar_v1.0.xlsx)

**Comment by drdiek** [comment]
The .swc files themselves are now located on the server in the folder attachment/neurites_swc.

**Comment by drdiek** [comment]
@nmsutton please refer to Issue #481 for guidance in how to deploy these new .swc files.

**Comment by drdiek** [comment]
@nmsutton the spreadsheet to be added to the database has been updated:

[attachment_neurite_rar_v1.0.xlsx](https://github.com/Hippocampome-Org/php/files/4263838/attachment_neurite_rar_v1.0.xlsx)

**Comment by nmsutton** [comment]
@drdiek I have completed this task. The new table is attachment_neurite_rar. Please review this work and if it looks acceptable please close this issue.
