### ISSUE TITLE
GAA: [neurites] Listing the proper species on the n-by-k Evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#488]
Currently under the SPECIES line in the bibliographic section currently lists strains and not species. In property_page_synpro.php at line 1339, the query is accessing the database table Fragment, whereas the proper table to access this information is the neurite table.

**Comment by nmsutton** [comment]
@drdiek I have completed this task. Please review this work and if it looks acceptable please close this issue.
