### ISSUE TITLE
GAA: [neurites] N-by-k Evidence page bibliographic entries that are currently listed as "NULL" should be omitted instead

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#489]
In the bibliographic section, if the PROTOCOL, SPECIES, Age/Weight, or Interpretation Notes entry is currently listed as "NULL," then the entry should be omitted.

**Comment by nmsutton** [comment]
@drdiek I have completed this task. The new table is attachment_neurite_rar. Please review this work and if it looks acceptable please close this issue.
