### ISSUE TITLE
GAA: [neurites] Craft the Evidence page for the Number of Contacts

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#491]
1) Change the title of the page to "Number of Contacts Evidence Page"
2) Format the Connection Details section to include a From neuron type, a To neuron type, the type of connection being described, and the parcel that the Axons and Dendrites are located in
3) Include the new explanatory comment: "The number of contacts per connected neuron pair is calculated by combining neuron type specific lengths and convex hulls of the presynaptic axons and the postsynaptic dendrites (evidenced below), and estimates of the mean inter-bouton and inter-spine (or inter-shaft contact) distances as well as of the axon-dendrite interaction distance."
4) List all of the axonal evidence with accompanying figure depicting the full neuron
5) List the Convex hull volume in the appropriate parcel
6) List the axonal length in the appropriate parcel
7) List all of the dendritic evidence with accompanying figure depicting the full neuron
8) List the Convex hull volume in the appropriate parcel
9) List the dendritic length in the appropriate parcel

![Number of Contacts](https://user-images.githubusercontent.com/4380011/75189103-7d87b280-571b-11ea-85c9-0510a0b144fa.jpg)

**Comment by nmsutton** [comment]
@drdiek Please help me to get some clarification about how to display figures. Should the connectivity evidence page figures be used and if a figure segmentation evidence image is detected then it is included as well? In this way, it would be a combination of preexisting connectivity figures together with new segmentation evidence images. This would use figure segmentation evidence file names listed in the attachment_connectivity table or where else? The attachment_connectivity figures are only names like “3100383.png” that match no figures I know where to find. In comparison, attachment_neurite for the NbyK matrices has filenames that specifically describe which figure segmentation evidence file names in the /neurite/ folder.

**Comment by drdiek** [comment]
@nmsutton the attachment_connectivity figure should not be used. Instead use the figures listed in the attachment_neurite table for the whole images, which are the figures in the /neurites/ folder, and the figures listed in the attachment_neurite_rar table for the compressed set of segmented images, which are the figures in the /neurites_rar/ folder.
Does this help to clarify things?

**Comment by nmsutton** [comment]
@drdiek thanks for the details. Please help me to further understand. We are using the connectivity evidence for the NbyN data and that is found by neuron1 (N1) and neuron (N2) identifying a fragment through Conndata that connects to an evidence id that is used to retrieve a figure (starting with the query in $query_to_get_conn_evidence). The attachment_neurite table returns figures given N1 and “neurite” column listed as S1:L1:N1. The NbyN matrix provides for each entry N1+subregion1 (S1), N2+S2. Given that in attachment_neurite each neuron can have its own image, should there be two images listed on the NbyN evidence page, one each for N1 and N2? 

You said that figures should come form the /neurite/ directory. Should images from the connectivity data not be used even if /neurite/ is missing them? We are using evidence from connectivity pages, that have more entries than in attachment_neurite, but if a figure is in connectivity data but not in that attachment_neurite than it should be not included? 

For figure segmentation evidence’s rar files, is that based on N1+’S1:All:A’ (attachment_neurite_rar’s “neurite_name” column entry) or N1+’S1:All:D’ (as well as the same for N2)? Or what “neurite_name” entry is it in the attachment_neurite_rar table for each neuron provided by the NbyN matrix? Given N1 and N2 can have different figure sementation rar files, should both rar files be included?

**Comment by drdiek** [comment]
@nmsutton for an NbyN Evidence page, you should ignore information coming from Conndata and related tables.
Giorgio stated that we will be re-using information from the connectivity matrix for the NbyN Evidence pages. He is correct, but just to an extent. We are using the old connectivity information, but only indirectly. The original connectivity matrix is based off of the morphology. The NbyN matrices are based off of the original connectivity matrix only in the fact that we now assume we know about the connections between two neuron types. Given such connection information, we now have brand new neurite-related tables from which you should be working.
You should consider the axonal entry (N1) separately from the dendritic entry (N2). At this point, you should retrieve the N1 information as if it came from an NbyK matrix. You then do the same for the N2 information.
In terms of the rar files and associated tables, you should retrieve them in a similar manner to the the regular png files associated with NbyK neurite information.

**Comment by nmsutton** [comment]
@drdiek I think this task may be completed now. Please look over the work and if it looks acceptable please close this issue.
