### ISSUE TITLE
GAA: [neurites] Craft the Evidence page for the Synaptic Probabilities

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#492]
1) Change the title of the page to "Synaptic Probabilities Evidence Page"
2) Format the Connection Details section to include a From neuron type, a To neuron type, the type of connection being described, and the parcel that the Axons and Dendrites are located in
3) Include the new explanatory comment: "The connection probability for a pair of neuron types is calculated by combining neuron-type-specific convex hulls of the presynaptic axons and the postsynaptic dendrites (evidenced below) and the volume of the anatomical parcel in which they overlap."
4) List all of the axonal evidence with accompanying figure depicting the full neuron
5) List the convex hull volume in the appropriate parcel
6) List the Figure segmentation evidence
7) Link the PNG download icon to the appropriate figure file
8) List all of the dendritic evidence with accompanying figure depicting the full neuron
9) List the convex hull volume in the appropriate parcel
10) List the Figure segmentation evidence
11) Link the PNG download icon to the appropriate figure file

![Synaptic Probabilities](https://user-images.githubusercontent.com/4380011/75190021-7661a400-571d-11ea-8bcc-c21935e9963a.jpg)

**Comment by nmsutton** [comment]
@drdiek I think this task may be completed now. Please look over the work and if it looks acceptable please close this issue.
