### ISSUE TITLE
CT: [neurites] Remove the hover-over window from the neuron-type names for the Somatic Distances of Dendrites and Axons matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#499]

**Comment by nmsutton** [comment]
@drdiek I think this task is completed now. Please look over the work and if it looks acceptable please close this issue.

**Comment by drdiek** [comment]
@nmsutton Can you please add the full name of the neuron type to the hover over as it appears for the NbyN matrices?

**Comment by nmsutton** [comment]
@drdiek I have added this. Please close if this looks complete.

**Comment by drdiek** [comment]
@nmsutton I am sorry to be so particular, but there is an extra blank line appearing in the hover over, which is after the neuron type name. Could you please remove that extra blank line?

**Comment by nmsutton** [comment]
@drdiek I have updated this to remove the blank line. Please check to confirm.
