### ISSUE TITLE
NM: [neurites] neurites_quantified and number_of_contacts spreadsheets are not ingesting without errors

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#500]
@nmsutton please provide me with copies of the spreadsheets and examples of the error codes and messages that are being produced, so I can help in debugging this situation.

**Comment by nmsutton** [comment]
@drdiek attached here are csv files Nikhil created that are not ingesting. csv2db seems to return no error from what I recall, just blank tables. I think you commented on this also weeks ago. Spreadsheets can be made by opening the csv files with a spreatsheet program and selecting import options. Do you have copies of the csv files that successfully ingest for you?

[examples.zip](https://github.com/Hippocampome-Org/php/files/4277326/examples.zip)

**Comment by drdiek** [comment]
@nmsutton try these versions.

[try these version.zip](https://github.com/Hippocampome-Org/php/files/4277367/try.these.version.zip)

**Comment by nmsutton** [comment]
@drdiek I am pleased to say the new versions you sent are ingesting successfully with all rows included. Please tell me, for future reference, do you have any idea why the other ones didn't work? If it is unknown that is ok.

**Comment by drdiek** [comment]
@nmsutton the problem was a number of special characters that had to be removed from figure captions and authors' names. It took quite an effort to track them all down. I also did some text cleaning along the way that Christopher and Keivan had neglected.

**Comment by nmsutton** [comment]
@drdiek Thanks very much for the work on this! I am curious, when csv2db didn't show an error in import, how did you find out that the work with the characters and text cleaning was needed? I might be able to use such methods if this situation ever can up again.

**Comment by drdiek** [comment]
@nmsutton it did show me an error during import, which is how I managed to track them all down. Besides being provided an error code, I was provided a few characters of context, which I used to localize the special characters. It was a fair amount of work.

**Comment by nmsutton** [comment]
@drdiek thanks for the further info. I don't know why I also didn't get the import errors but if you agree this is completed let's please close this.
