### ISSUE TITLE
DWW: [neurites] Strange characters still appearing in some of the figure captions

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#501]
As far as I can tell from the database, which I dumped from the server the other day, the weird characters should not be appearing in the example below, but they are.
![strange_characters](https://user-images.githubusercontent.com/4380011/76690588-ecb83e80-6617-11ea-960b-3116c26b49e3.jpg)

**Comment by nmsutton** [comment]
@drdiek I have solved this issue. It appears it was in the fragment csv files I generated. I reexported the data from the db and it appears to be fixed, [Example 1](http://www.hippocampome.org/phpdev/property_page_synpro.php?id_neuron=1000&val_property=DG_H&color=red&page=1&sp_page=dal) which you included in your screen shot. The dev db on the cng server now has the data not garbled. Please review this and if finished close it.

**Comment by drdiek** [comment]
@nmsutton Your fragment.csv should have been free of strange characters. Somehow I must not have passed on a fully cleaned .csv file to you.
