### ISSUE TITLE
DWW: [neurites]: In the hover over window for the neuron type names, also list the full name of the neuron type

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#502]
Besides the values associated with the axons and dendrites, please also list the full name of the neuron type as it appears for the NxN matrices.

**Comment by nmsutton** [comment]
@drdiek I have added this for the Axon and Dendrite lengths matrix as well as Somatic Distances of Dendrites and Axons matrix. Please close if this is complete.
