### ISSUE TITLE
CT: [neurites] Add in "axon (from)" and "dendrite (to)" toggles to the NxN Evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#503]
For these toggles you should be able to re-use the code from the original connectivity Evidence pages. You do not have to worry about replicating the "potential" toggle for these NxN Evidence pages.

**Comment by nmsutton** [comment]
@drdiek please close this issue based on the email I just sent about checkboxes feedback. Thank you for you work on posting this but Giorgio does not want this on the pages.
