### ISSUE TITLE
GAA [connectivity] Modify php code to correctly read in and interpret the mec_lec_flag and is_flag

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#509]
@nmsutton First of all, map.py needs to be modified. Right now at line 463, it incorrectly reads in a '0' as connection_status = 'negative.' It should be assigning a value of '-1' to 'negative.'

In getMorphology.php, the mec_lec_flag and is_flag portions of the code that deal with reading in the pc_flag and soma_pcl_flag need to be excised. A totally separate procedure needs to be coded to read in the new flags. More instructions to come.

**Comment by drdiek** [comment]
@nmsutton I now think map.py needs to be slightly overhauled. Instead of assigning values of 'positive' or 'negative,' the connection_status_string parameters needs to be changed to integer connection_status parameters.

In getMorphlogy.php, I would try to add a new section after the reading in of the pc_flag and soma_pcl_flag that looks something like:
// query to get mec_lec_and_is flag associated with all types
$query_mec_lec_and_is_flag="SELECT DISTINCT e.Type1_id,e.Type2_id,e.mec_lec_and_is_flag 
FROM Conndata e, Type t1, Type t2
WHERE t1.id=e.Type1_id and t1.id=e.Type2_id and e.mec_lec_and_is_flag is not null
GROUP BY t1.id
ORDER BY t1.position";
Of course, I leave it to you to make this work, as I am not sure I know what I am doing here, but hopefully you get the idea. :)

Later in getMorphology.php, the section where the mec_lec_and_is_flag is evaluated needs to be re-worked. I think the following line can be kept as is:
if(($row_id==4056&&$col_id==4036)||($row_id==4056&&$col_id==4078)||($row_id==4031&&$col_id==4036)||($row_id==4031&&$col_id==4078)){
            	$pon_conn_display_array[$row_index][$col_index]=NO_CONNECTION;
            }
However, the rest of the section needs to be reworked, whereby the mec_lec_and_is_flag is evaluated such that a value of -1 leads to $pon_conn_display_array[$row_index][$col_index]=NO_CONNECTION for a particular combination of $row_index and $col_index. Unfortunately, my level of php is not sophisticated enough to know how to make this happen, so I can only provide general guidance.

**Comment by nmsutton** [comment]
@drdiek thanks for the further guidance here. A question is that, to have e.mec_lec_and_is_flag in Conndata e that would need to be a new column added to that table. Are you wanting conndata.csv to have the values for that column hard coded into the csv file or auto-generated with map.py? Could either be an option?

**Comment by drdiek** [comment]
@nmsutton It should definitely be auto-generated with map.py. Like I tried to describe, the code in map.py already produces a column in Conndata call "connection_status." The problem is that connection_status is a string value and the code in getMorphology.php is expecting an integer value. However, the code in getMorphology needs revamping, so I suppose it could easily be restructured to check for string values rather than integers. Either way, the code in map.py is currently wrong in that it maps a '0' into a 'negative,' when it should be mapping a '-1' into a 'negative.'

**Comment by drdiek** [comment]
@nmsutton Here is an update based on an email from @k1moradi. 
In map.py, when interpreting the connection_status_string from the conndata.csv spreadsheet:
1: known connections based on evidence (they are not just potential)
0: refuted connections
-1: axo-dendritic overlaps (potential connections) that are impossible in as much as we know, like LEC to MEC local connection, or IS to principal neuron connection
Currently, '1' is mapped to 'positive' and '0' is mapped to 'negative.' What we need is to add a mapping for '-1.' I would suggest something like 'impossible.'

**Comment by drdiek** [comment]
@nmsutton In looking through map.py some more, I have discovered that the table TypeTypeRel may already have the information we need for getMorphology.php. Take a look at lines 420-446. What I do not understand is why some of these lines are doing some of the same job that the "def condata_to_conndata(self)" function seems to be doing. Each set of code reads from a different .csv spreadsheet, although both .csv spreadsheets are derived from the same .xslx spreadsheet.

**Comment by drdiek** [comment]
@nmsutton Line 430 of map.py should be converted from:
if connection_status_string == '1':
to:
if (connection_status_string == '1' or connection_status_string == '4' or connection_status_string == '5'):
After making this change, we can then use TypeTypeRel in getMorphology.php.

**Comment by k1moradi** [comment]
Since any "connection_status_string" greater than 0 validates potential connections, may I suggest changing the code to:

if int(connection_status_string)>0:

**Comment by k1moradi** [comment]
empty=no evidence to our knowledge, 
-1=refuted connection inference-based, 
0=refuted connection evidence-based, 
1=validated chemical synapses, 
2=validated - only electrical synapse, 
3=validated - both electrical and chemical, 
4=validated - only autapses, 
5=validated - both autapses and chemical synapses with other neurons, 
6=validated - all types (synapse, autapses, and electrical synapses), 
7=electrical or chemical synapses mutually exclusive

**Comment by k1moradi** [comment]
If we do not consider electrical synapses, then 

if int(connection_status_string)>0 and int(connection_status_string) != 2:

**Comment by nmsutton** [comment]
@drdiek I think the connectivity matrix may be corrected now. I added the line in getMorphology that uses $connection_status_array[$row_id][$col_id]=='negative' to set "no connection". I have uploaded the new version of the matrix to phpdev. I ran SQL to look for test cases: 
```
SELECT distinct Type1_id, Type2_id, connection_status FROM hippocsv2dbome.TypeTypeRel 
WHERE connection_status='negative' AND Type1_id=6078;
```
This returns all negative entries for LEC LVI Multipolar-Pyramidal (6078) and out of 11 none show on the matrix. Also, the session_matrix_conn.json file has reduced in size after the code revision that indicates less matrix content is created; that matches removing entries with 'negative' status. Can you please check this further to see if it indeed has corrected the issue? Perhaps the query:
```
SELECT distinct Type1_id, Type2_id, connection_status 
FROM hippocsv2dbome.TypeTypeRel 
WHERE connection_status='negative' AND Type1_id>=6000;
```
can help with supplying examples to test.

One note is that I did not change anything in map.py involving conndata_to_conndata and 
elif connection_status_string == '5': connection_status = 'positive'. During our video meeting there was some mention of needing to map connection_status 4 and 5 to positive, but I did not change anything related to that. Is something like that needed? I think this was mentioned related to the way TypeTypeRel is created, but connection_to_connection() creates that in map.py (using known_connections.csv). Does connection_to_connection() and the rest of map.py seem fine or was something in that suppose to be updated?

There was also mention of processing the "Connection?" column in conndata.csv. I use TypeTypeRel and not Conndata to find the 'negative' entries, so is that relevant anymore (anything needed with that)?

**Comment by drdiek** [comment]
@nmsutton In looking at the stats that appear on the Connectivity matrix page, i.e. 1142 potential excitatory connections and 1977 potential inhibitory connections, I notice that the total is 3119, which means that one connection is missing. In comparing the downloadable netlist file with the one that Giorgio circulated this morning, I notice that 1000 -> 2036 is missing, i.e. one of the potential excitatory connections. Any ideas as to why it might not be showing up?

I do think that map.py needs to be updated, as per @k1moradi's suggestion. Line 430 needs to be changed from:
if connection_status_string == '1':
to:
if int(connection_status_string)>0 and int(connection_status_string) != 2:

The Connection? column from conndata.csv can be safely ignored.

**Comment by nmsutton** [comment]
@drdiek in TypeTypeRel there is a row:
`'1000', '2036', 'negative'`
it would set that connection to "no connection" due to that. Should the underlying csv file be changed to not have that entry?

**Comment by drdiek** [comment]
@nmsutton This is very curious, because in known_connections.csv, there is no integer assigned to the connection, meaning that is is merely a potential connection. I, therefore, do not understand where the notion that the connection is 'negative' is coming from.

**Comment by nmsutton** [comment]
@drdiek I will try to further investigate what is causing the row

**Comment by drdiek** [comment]
@nmsutton I just found an old version of known_connections.csv, and there is a 0 assigned to the connection. The latest version of known_connections.csv, has no integer assigned to it. therefore, I must conclude that you used an old version of the file to generate the database the last time you did so.

**Comment by nmsutton** [comment]
@drdiek I came to the same conclusion before I read your latest message here and I am pleased to report that once I ingested the newest known_connections.csv the netlist now has 3120 neuron pair connections (thanks for looking into it on your side as well). I have uploaded the updated version of the database to hippodevome and uploaded the latest files to phpdev. Please d/l the netlist from phpdev and do any other approaches to check if now the connectivity matrix issue is fixed.

**Comment by nmsutton** [comment]
@drdiek Even though this issue is closed, for the record, I have added to map.py line 430:
```
[1] if (connection_status_string == '1' or connection_status_string == '4' or connection_status_string == '5'):
```
this is instead of:
`[2] if int(connection_status_string)>0 and int(connection_status_string) != 2:`
because [2] was causing programming issues after testing.
