### ISSUE TITLE
GAA: clarification of all mixed expression differences (last checked 20140509 - DWW)

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#51]
We need a human readable single sentence at the top of the Evidence Page that summarizes the reason for the mixed expression pattern.

Looking at the mixed evidence of CCK in DG gc, it occurs to me that it would be nice to explain at the top of these "orange triangle" pages the source of protocol or species difference. In this case, we could just say "Positive for mouse and negative for rat" (in other case there might be "gene is expressed but protein is not" etc.). In the specific, it seems in fact that the evidence might be mixed for rats! The one piece I looked at (Chandy et al., 1995) indicates CCK+ in a very small fraction of boutons (I assume the others were CCK-). Is the proportion in the mouse much greater?

**Comment by dhamilt5** [comment]
CLR changes for property_page_markers.php
From:Christopher Rees
Mon 3/2/2015 1:25 PM
To:David J Hamilton (dhamilt5@gmu.edu) <dhamilt5@gmu.edu>
property_page_markers.php
Hi David,
The file I modified is attached and my changes are summarized below:
Modified line 19411:
Old version: $expression_values = explode('‐', $_REQUEST['color']); New version: $expression_values = explode('‐', $color);
Deleted (or you can comment out) lines 19416‐19425
Old version:
if ($conflict_note)
$conflict_note = "‐‐ $conflict_note"; print("CONFLICT NOTE:" . $conflict_note);
if ($val_property == 'Gaba‐a‐alpha')
print ("&nbsp <strong>GABAa &alpha;1 ($color) $conflict_note</strong>");
else if ($val_property == 'alpha‐actinin‐2')
print ("&nbsp <strong>&alpha;‐act2 ($color) $conflict_note</strong>");
else
print ("&nbsp <strong>$val_property ($color) $conflict_note</strong>");
In their place, I added the following large block, which goes from line 19427‐19572 in the ATTACHED file:
New version:
expression', 'positive'); getProperty_id(0);
///////////// CLR added this block /////////////
$conflict_note = $evidencepropertyyperel ­> getConflict_note();
$species_prot_diff = false;
if ($conflict_note == "positive" || $conflict_note == "negative")
else {
$conflict_note = "";
if ($conflict_note == "species/protocol differences") {
$species_prot_diff = true; // positive +
$property ­> retrive_ID(1, $subject, 'has $property_id_pos = $property ­>
$query = "SELECT Evidence_id FROM hippocampome.evidencepropertytyperel WHERE Type_id=$type_id and
Property_id=$property_id_pos";
mysql_fetch_row($rs))
$rs = mysql_query($query);
$pos_array = Array();
$pos_summary = Array( Array(0, 0), Array (0, 0)); while(list($id_evidence_pos) =
{
$evidencemarkerdatarel ­> retrive_Markerdata_id($id_evidence_pos); getMarkerdata_id_array(0);
getExpression(); $expression);
$animal); $protocol);
$protocol); $ani_prot_values);
$id_markerdata1 = $evidencemarkerdatarel ­>
$markerdata ­> retrive_info($id_markerdata1);
//$expression = $markerdata ­>
//$expression = preg_replace('/[\[\]"]/', '',
$animal = $markerdata ­> getAnimal(); $animal = preg_replace('/[\[\]"]/', '',
$protocol = $markerdata ­> getProtocol(); $protocol = preg_replace('/[\[\]"]/', '',
if ($protocol != "unknown") { $ani_prot_values = Array(); array_push($ani_prot_values, $animal); array_push($ani_prot_values,
array_push($pos_array,
if ($animal=="rat" && $protocol=="immunohistochemistry") $pos_summary[0][0] = 1;
elseif ($animal=="rat" &&
$protocol=="mRNA") $pos_summary[0][1] = 1; $protocol=="immunohistochemistry") $pos_summary[1][0] = 1;
elseif ($animal=="mouse" && }
}
$pos_array = array_map("unserialize", array_unique(array_map("serialize", $pos_array)));
$protocol=="mRNA") $pos_summary[1][1] = 1;
expression', 'negative');
// negative ­
$property ­> retrive_ID(1, $subject, 'has
$property_id_neg = $property ­> getProperty_id(0);
$query = "SELECT Evidence_id FROM hippocampome.evidencepropertytyperel WHERE Type_id=$type_id and
Property_id=$property_id_neg";
mysql_fetch_row($rs))
$rs = mysql_query($query);
$neg_array = Array();
$neg_summary = Array( Array(0, 0), Array (0, 0)); while(list($id_evidence_neg) =
{
$evidencemarkerdatarel ­> retrive_Markerdata_id($id_evidence_neg); getMarkerdata_id_array(0);
getExpression(); $expression);
$animal);
$id_markerdata1 = $evidencemarkerdatarel ­>
$markerdata ­> retrive_info($id_markerdata1);
//$expression = $markerdata ­>
//$expression = preg_replace('/[\[\]"]/', '',
$animal = $markerdata ­> getAnimal(); $animal = preg_replace('/[\[\]"]/', '',
elseif ($animal=="mouse" &&
$protocol = $markerdata ­> getProtocol();
￼CLR changes for property_page_markers.php - David Hamilton
$protocol = preg_replace('/[\[\]"]/', '',
if ($protocol != "unknown") { $ani_prot_values = Array(); array_push($ani_prot_values, $animal); array_push($ani_prot_values,
array_push($neg_array,
$protocol);
$protocol); $ani_prot_values);
if ($animal=="rat" && $protocol=="immunohistochemistry") $neg_summary[0][0] = 1;
elseif ($animal=="rat" &&
$protocol=="mRNA") $neg_summary[0][1] = 1; $protocol=="immunohistochemistry") $neg_summary[1][0] = 1;
elseif ($animal=="mouse" && }
}
$neg_array = array_map("unserialize", array_unique(array_map("serialize", $neg_array)));
$protocol=="mRNA") $neg_summary[1][1] = 1;
</strong>"); ($color$conflict_note)</strong>");
width='40%'>";
if ($species_prot_diff) {
echo "<TABLE> <TR> <TD width='15%'></TD> <TD
// first table option
"</TD> <TD>" . $row[1] . "</TD></TR>";} </TD> <TD>" . $row[1] . "</TD></TR>";}
</TD> <TD>" . $row[1] . "</TD></TR>";}
"</TD> <TD>" . $row[1] . "</TD></TR>";} }
if ($i == 0) {echo "<TD>" . $row[0] . " else {echo "<TR> <TD></TD> <TD>" . $row[0] .
}
}
$conflict_note = ": " . $conflict_note; // CLR added
if ($val_property == 'Gaba­a­alpha') print ("&nbsp <strong>GABAa &alpha;1
($color$conflict_note)</strong>");
else if ($val_property == 'alpha­actinin­2')
print ("&nbsp <strong>&alpha;­act2 ($color$conflict_note)
else
print ("&nbsp <strong>$val_property
echo "<HR><TABLE class='table_neuron_page2' padding='10'> <TR> <TD><strong>Positive</strong></TD>";
foreach ($pos_array as $i => $row) {
if ($i == 0) {echo "<TD>" . $row[0] .
elseif ($animal=="mouse" &&
else {echo "<TR> <TD></TD> <TD>" . $row[0] . " }
echo "<TR> <TD><strong>Negative</strong></TD>"; foreach ($neg_array as $i => $row) {
echo "</TABLE><HR>";
//Second table option
echo "</TD> <TD width='5%'></TD> <TD width='40%'>";
echo "<HR><TABLE class='table_neuron_page2' padding='10'> <TR> <TD></TD> <TD><strong>Immunohistochemistry</strong></TD> <TD>
<strong>mRNA</strong></TD> </TR>"; <center>";
echo "<TR> <TD><strong>Rat</strong></TD> <TD> //if rat & immuno
if ($pos_summary[0][0] == 1 && $neg_summary[0][0])
elseif ($pos_summary[0][0] == 1) echo "+"; elseif ($neg_summary[0][0] == 1) echo "­"; else echo "unknown";
echo "</center></TD> <TD><center>";
//if rat & mRna
if ($pos_summary[0][1] == 1 && $neg_summary[0][1])
elseif ($pos_summary[0][1] == 1) echo "+"; elseif ($neg_summary[0][1] == 1) echo "­"; else echo "unknown";
echo "</center></TD> </TR>";
echo "<TR> <TD><strong>Mouse</strong</TD> <TD> // mouse & immuno
if ($pos_summary[1][0] == 1 && $neg_summary[1][0])
elseif ($pos_summary[1][0] == 1) echo "+"; elseif ($neg_summary[1][0] == 1) echo "­"; else echo "unknown";
echo "</center></TD> <TD><center>";
// mouse & mRNA
if ($pos_summary[1][1] == 1 && $neg_summary[1][1])
elseif ($pos_summary[1][1] == 1) echo "+"; elseif ($neg_summary[1][1] == 1) echo "­"; else echo "unknown";
echo "</center></TD> </TR>";
echo "</TABLE><HR>";
echo "</TD> </TR></TABLE>";
echo "+,­";
echo "+,­";
<center>";
echo "+,­";
echo "+,­";
}
///////////// end of CLR changes /////////////
Thanks, David! Let me know if you have questions. Christopher

**Comment by dhamilt5** [comment]
This code was incorporated into the master property_page_markers.php on 201503280750. The resultant table at the top of the marker evidence page appears to the user, only if the anonymous user is disabled, so as to only be visible for internal curation use, not production.
