### ISSUE TITLE
GAA: [neurites] Upgrade the Connection Probabilities tool

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#513]
From Giorgio: "The “old” tool to re-calculate synaptic probability with a user’s choice of parameters was designed at the time when we hadn’t figured out yet how to extract number of contacts from the lengths. Now, however, the “number of contacts” option should be removed. Only  Dendritic spine distance, Inter-bouton distance, and Radius of interaction should be left as choices. Moreover, currently the tool outputs a single value (the connection probability) per parcel. Instead, given our new and improved formulation, it should output two sets of results: connection probabilities and number of contacts per connected pair, in distinct rows each clearly marked."

* Please edit connprob.php so that the misspelled variable 'dentrite' is correctly spelled as 'dendrite.'

To address the new calculation of the number of contacts, line 90 of connprob.php needs to be commented out, and the following lines need to be added just after line 99:
for (var i = 0; i < axons.length; i++) { // step over local parcels
            	num_contacts[i] = (4 * c * length_axons[i] * length_dendrites[i]) / (volume_axons[i] + volume_dendrites[i]);
}
@nmsutton I leave it as an exercise for you to figure out how to get the volume_axons and volume_dendrites values read in. The length_axons and length_dendrites are read in from .csv files stored in the data folder. Perhaps a similar solution for the volumes is needed. If you need help compiling such files, please let me, or better yet Carolina, know.

What is now line 105 in connprob.php needs to be changed to read:
final_result.push((c * ((length_axons[i] * length_dendrites[i]) / volumes_array[i])) / num_contacts[i]);

It is likely that lines in the function targetSelected() at line 158, which involve the variable 'contacts' will need to be commented out.

I do not know how to display the new num_contacts values the way the connection probabilities currently are, but both sets of values will need to be displayed and properly labeled as such.

**Comment by drdiek** [comment]
@nmsutton Here are the new .csv files containing the convex hull volumes that need to be read in for the volume_axons[i] and volume_dendrites[i] variables. They should be placed in the data/ folder, which is where the .csv files with lengths values are currently stored.

[convex_hull_volumes.zip](https://github.com/Hippocampome-Org/php/files/4414718/convex_hull_volumes.zip)

**Comment by nmsutton** [comment]
@drdiek I have some good news, I have been able to work with the code to get the data in convex_hull_volumes.zip loaded into the page and parsed. It is correct that the volumes are present in the values:```

.....................|.Neuron.ID.|.SMo..............|.SMi................|.SG.|.H.........
DG_Granule.|.1000.........|........................|.......................|.......|.[1].85681348.19
.....................|.................|.29868963.17..|.4753505.027.|.......|............

``` 
Where [1] is axonal volume in DG_Granule, H?

**Comment by drdiek** [comment]
@nmsutton Yes, that is correct.

**Comment by nmsutton** [comment]
@drdiek It appears I may have completed this. Please review this and inspect if it is correctly completed.

**Comment by drdiek** [comment]
@nmsutton When there is no Synaptic Probabilities value, it current lists "NaN." Can you please instead have it display a zero?

**Comment by nmsutton** [comment]
@drdiek Thanks for the feedback. A question that comes up for me about that is that there can be a lack of data about volumes and other values (based on the source csv files) that produces a "NaN" value, not an actual 0 probability. I would have a concern about reporting 0 probability instead of a message "Not Available" or something. If you recommend that 0s be reported instead of that I will add them, but I wouldn't want a confusion for a user that 0 probability was reported when in fact data was just missing to report a probability.

**Comment by drdiek** [comment]
@nmsutton I think we can safely assume that when there is no volume value reported for a particular parcel, that the value is actually zero. That is, if no neurites exist in a particular parcel, the probability of a synapse forming is zero and the number of contacts is zero.

**Comment by nmsutton** [comment]
@drdiek Thanks for the info. I have applied an update where all NaN values should be 0 now. The update makes any NaN in length_neurite, volume_neurite, number_of_contacts, or synaptic_probability into 0 values that are computed in the formulas. Please tell me if this issue now looks complete.

**Comment by drdiek** [comment]
From Giorgio: "Similar to the logic of the paper, I think we should first show the probability and call it “Probability of connection per neuron pair” and then the contacts and call it “number of contacts per connected neuron pair”.
Also we should only display whatever number of significant digits that makes reasonable sense statistically/scientifically. Claiming that the number of contacts is 2.9394208161764657 is ludicrous :-}"

**Comment by nmsutton** [comment]
@drdiek For record-keeping here, I have now updated the value to show "0" at the end rather than crop that last digit that Giorgio requested be saved. An example is pre- DG Mossy Molden post- DG Hicap Dend:2 Bouton:2 Radius:2, creates a probability total of "0.0150".

**Comment by drdiek** [comment]
From Giorgio: "... is it possible to reduce the space between the table titles and the tables, and to increase the numerical fonts in the tables?"

**Comment by nmsutton** [comment]
@drdiek I have now changed the title positions and font sizes.

**Comment by drdiek** [comment]
@nmsutton When I typed in pre-Mossy MOLDEN and post-HICAP, with 2 - 2 - 2, the number of contacts for SMi is listed as 1.4. This should be 1.40, as per Giorgio's previous request.

What I am still trying to figure out is how to execute Giorgio's requested 1 - ((1-Px)*(1-Py)*...) algorithm for the summation of probabilities. I will dive back into this tomorrow morning.

**Comment by nmsutton** [comment]
@drdiek I only applied Giorgio's formula to the summing of synaptic probabilities (SP) for a total, not summing of number of contacts (NOC) for a total (he only mentioned it in reference to the SP not NOC). Should I also apply the formula to the summing of the number of contacts?

**Comment by drdiek** [comment]
@nmsutton Ah, I had not seen that you had corrected for Giorgio's formula already.

No, the formula does not apply to the number of contacts.

Just to give you a head's up, there is an additive factor that works into the formula for the number of contacts per parcel. I am still discussing the exact value of that factor with Carolina. I will let you know when that has been resolved.

**Comment by drdiek** [comment]
@nmsutton Here is how line 148 on connprob.php needs to be modified:

num_contacts[i] = (1 / length_axons.length) + (4 * c * length_axons[i] * length_dendrites[i]) / (volume_axons[i] + volume_dendrites[i]);

The idea is that there is an assumed single point of contact somewhere among the parcels involved, such as the 4 for dentate gyrus; therefore, that single point of contact gets evenly distributed across all of the parcels. 

Do you want to make the change, or should I?

**Comment by nmsutton** [comment]
@drdiek I have now updated the formula and uploaded the new version to phpdev. Thanks for obtaining the info. and providing the formula. Also, I changed the displayed number of connections values to only 1 decimal place because Carolina said she wanted that to match the number of contacts matrix. Have I now completed all the work that was requested for this issue?

**Comment by drdiek** [comment]
@nmsutton I am confused. The matrix displays 2 decimal places, not 1.

**Comment by nmsutton** [comment]
@drdiek for example, a test total for number of contacts is "4.5". I looked up "decimal place" and that defined as "the position of a digit to the right of a decimal point" ([link](http://english.oxforddictionaries.com/decimal%20place)). Doesn't 4.5 only have 1 decimal place? Either way, that is what I meant, one number to the right of the decimal. Thank you for checking about this in any case just to be sure.

**Comment by nmsutton** [comment]
@drdiek I just checked and I see your point that on the NOC matrix it has 2 decimal places. I will update the tool to match that. Thanks for catching that. Just to confirm, when "3 significant digits" is stated that means 2 decimal places, right?

**Comment by drdiek** [comment]
@nmsutton Yes, that is correct.

**Comment by nmsutton** [comment]
@drdiek Thanks, Giorgio wrote:
> 4 significant digits for probability and 3 for numbers of contacts

and therefore I have updated the tool to match that. This also fits with Carolina stating:
> digits for the number of contacts to be consistent with our matrix

and it seems they should be displayed in the requested way now. Does it appear there are any other things need with this issue?

**Comment by drdiek** [comment]
@nmsutton I have just come across a problem with the way that we are now calculating the number of contacts. Right now, we split up the one assumed contact point among all of the parcels of a particular subregion. Instead, we should be splitting up that one contact point among all of the parcels that have non-zero values in them. See the attached figure below for how the current system is failing.
![Screen Shot 2020-04-04 at 19 37 18](https://user-images.githubusercontent.com/4380011/78463587-81a8d780-76ac-11ea-962c-c45b1a1fe28c.jpg)

**Comment by nmsutton** [comment]
@drdiek I have an idea of how to fix this and will work on it now.

**Comment by nmsutton** [comment]
@drdiek it appears I may have fixed this. I have uploaded the changes to phpdev and Github. Please check it and see if it works as wanted. Code added is below:
```
let noc_non_zero = 0;
for (var i = 0; i < length_axons.length; i++) {
                let noc = (4 * c * length_axons[i] * length_dendrites[i]) / (volume_axons[i] + volume_dendrites[i]);
                if (noc!=0) {
                    noc_non_zero = noc_non_zero + 1;
                }
            }
            for (var i = 0; i < length_axons.length; i++) {
                ...
                let noc = (4 * c * length_axons[i] * length_dendrites[i]) / (volume_axons[i] + volume_dendrites[i]);
                if (noc!=0) {
                    num_contacts[i] = (1 / noc_non_zero) + (4 * c * length_axons[i] * length_dendrites[i]) / (volume_axons[i] + volume_dendrites[i]);
                }
```

**Comment by drdiek** [comment]
@nmsutton It seems to check out.

**Comment by drdiek** [comment]
@nmsutton I have reopened this Issue until we resolve Giorgio's new proposed method for distributing the extra +1 contact across the non-zero-valued layers.
