### ISSUE TITLE
GAA: [neurites] Correct the maxima and minima calculations for the somatic distances hover-over windows

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#514]
From Giorgio: "... for every neurite path and parcel we compute a minimum (e.g. entrance crossing point) and a maximum (exit crossing point), then we take the average of these values as the ‘average’ distance for that neurite in that parcel. Say we have 3 paths for a given neurite and parcel. We thus calculate the mean and standard deviation of the [3] average[s]. The ‘minimum’ that we report in the online matrix (similar to the whiskers in Fig. 6) should now be the minimum of minima (not the minimum of averages) and the ‘maximum’ should be the maximum of maxima (not the maximum of averages). I suspect that we are calculating this incorrectly because the axonal distance for semilular in SL has min=max=mean, which could not possibly be the case in the correct calculation."

In the neurite_quantified.csv file, the minima are found in column O: 'Entry point,' the maxima are found in column N: 'Mean_path_length,' and the averages are found in column P: 'Average.' In the neurite_quantified database table, these values are found in 'entry_point,' 'mean_path_length,' and 'average,' respectively. For the Semilunar Granule cells (Unique ID: 1001) to which Giorgio referred, there are 6 separate entries for DG:SMo:D. The mean and standard deviation of the 6 averages come out to be mean(335.1055556, 339.5611111, 299.9388889, 162.0269231, 184.7961538, 181.9884615)=250.5695157 and standard deviation=75.68847109. The minimum of the minima comes out to be min(228.211111, 228.211111, 228.211111, 102.284615, 102.284615, 102.284615)=102.284615. The maximum of the maxima comes out to be max(371.6666667, 450.9111111, 442, 221.7692308, 267.3076923, 261.6923077)=450.9111111.

**Comment by drdiek** [comment]
@nmsutton Under Giorgio's direction, three of the column titles in the neurite_quantified.csv file have been changed to be more understandable. Column N is now 'Max_path_length,' column O is now 'Min_path_length,' and column P is now 'Avg_path_length.' Hopefully, these will make more sense to you. I have also changed the necessary lines in map.py and models.py.

**Comment by nmsutton** [comment]
@drdiek thanks for the help with the column titles. I have now regenerated the somatic distances matrix with the updated values. Please help review if this looks completed.

**Comment by drdiek** [comment]
@nmsutton When I hover over DG Granule A:CA3:SL, I get a maximum value of 0.00, which is incorrect. Can you please look into this?

**Comment by nmsutton** [comment]
@drdiek In the query:
```
SELECT * FROM neurite_quantified WHERE neurite_quantified.unique_id=1000 
AND neurite_quantified.neurite='CA3:SL:A' AND avg_path_length!='';
```
max_path_length has blank values. That is why it is reporting 0 on the matrix. Should there be values there that are missing? Thanks for checking.

**Comment by drdiek** [comment]
@nmsutton I am still waiting to hear back from Carolina on the missing values.

**Comment by drdiek** [comment]
@nmsutton Carolina provided an updated spreadsheet, so I have updated neurite_quantified.csv in the repository. After you perform a new import, this problem should be solved.

**Comment by nmsutton** [comment]
@drdiek thanks, I will regenerate the db a little later in the day.

**Comment by nmsutton** [comment]
@drdiek I have recreated the db and uploaded the new content to phpdev. Looks like it fixed the issue.

**Comment by drdiek** [comment]
@nmsutton Unfortunately, there are still some problems. For DG Granule (UID 1000), for A:CA3:SL the mean is greater than the maximum. For DG Granule, for A:CA3:SP, the mean is less than the minimum. For Hilar Ectopic Granule (UID 1041), the maximum value is being reported as zero.

**Comment by drdiek** [comment]
@nmsutton Carolina sent me a revised spreadsheet. However, it has more entries than the previous version. I am awaiting confirmation that she in fact added some new entries. Once I hear back from her, I will update the necessary spreadsheet to be ingested into the database.

**Comment by drdiek** [comment]
@nmsutton I have now updated the spreadsheet neurite_quantified.csv. Once you perform a new ingest, this problem should be solved.

**Comment by nmsutton** [comment]
@drdiek I have now ingested the new neurite_quantified.csv and number_of_contacts.csv files and uploaded the new db and files to phpdev. Does it appear this issue if now resolved?

**Comment by drdiek** [comment]
@nmsutton No, the issue is not resolved. For DG Granule (UID 1000), for A:CA3:SL, the mean is still greater than the maximum. For DG Granule, for A:CA3:SP, the mean is still less than the minimum. However, for Hilar Ectopic Granule (UID 1041), the maximum value is no longer being reported as zero. I will continue my investigations.

**Comment by nmsutton** [comment]
@drdiek for testing, a way to check DG Granule - A:CA3:SL is to run this:
Query:
```
SELECT CAST(STD(CAST(avg_path_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS std_sd, 
 CAST(AVG(CAST(avg_path_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg, 
 CAST(COUNT(CAST(avg_path_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS count_sd, 
 CAST(AVG(CAST(avg_path_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg_trunk, 
 CAST(min_path_length AS DECIMAL(10,2)) AS min_sd, CAST(max_path_length AS DECIMAL(10,2)) 
 AS max_sd FROM neurite_quantified WHERE neurite_quantified.unique_id=1000 
 AND neurite_quantified.neurite='CA3:SL:A' AND avg_path_length!='';
```
Result:
```
std_sd, avg, count_sd, avg_trunk, min_sd, max_sd
'45.51', '403.41', '2.00', '403.41', '315.51', '400.28'
```

**Comment by nmsutton** [comment]
@drdiek I found there is 2 max_path_length values reported:
Query:
```
SELECT max_path_length
FROM neurite_quantified WHERE neurite_quantified.unique_id=1000 
 AND neurite_quantified.neurite='CA3:SL:A' AND avg_path_length!='';
```
Result:
```
max_path_length
'400.28'
'582.31'
```
Wasn't there only suppose to be 1 max_path_length reported? Should the queries look for the max() or min() of the max_path_length and min_path_length? In general, is this an error or something the queries should account for?

**Comment by drdiek** [comment]
@nmsutton As per Giorgio's very first quote up above: "The ‘minimum’ that we report in the online matrix (similar to the whiskers in Fig. 6) should now be the minimum of minima (not the minimum of averages) and the ‘maximum’ should be the maximum of maxima (not the maximum of averages)."

**Comment by nmsutton** [comment]
@drdiek I have now updated the code to include the minimum of minima and maximum of maxima and it appears it may have fixed the issue. Please take a look and tell me if this looks completed.

**Comment by drdiek** [comment]
@nmsutton It looks good.
