### ISSUE TITLE
GAA: [markers] Update interpretation for MEC LII Stellate cell Evidence

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#515]
From Giorgio: "I noticed a possible bug in our evidence reporting on the main site. When I click the evidence for molecular subtypes in MEC L2 stellate for CB, the Kitamura-Tonegawa ‘Island cells control temporal association memory’ paper is marked “positive” but seems to support  a negative interpretation, no?"

The markerdata.csv file has been properly updated, so a fresh import into the database should fix this problem. Once done, the "EXPRESSION" in the picture below will change from "positive" to "negative."

![Screen Shot 2020-03-30 at 17 32 48](https://user-images.githubusercontent.com/4380011/77964538-33ab6280-72ad-11ea-893c-ade0290ce139.jpg)

**Comment by nmsutton** [comment]
@drdiek I have done a fresh import of the matrix with the updated markerdata.csv but in the link it still appears 'negative' ([link reference](http://www.hippocampome.org/phpdev/property_page_markers.php?id_neuron=6003&val_property=CB&color=positive-negative&page=markers)). What else might need to be done?

**Comment by drdiek** [comment]
@nmsutton Give me a minute to re-check the database itself. I thought I knew where the information was coming from, but perhaps I missed something.

**Comment by drdiek** [comment]
@nmsutton I did not read your note clearly enough, and you did not read my original note clearly enough. Before, the expression was incorrectly reporting as 'positive.' Now, it is correctly reporting as negative, as expected.
