### ISSUE TITLE
GAA: [neurites] None of the NxN Evidence pages is showing any values in the bibliographic section

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#522]
All of the values are either zero or blank.

**Comment by nmsutton** [comment]
@drdiek I suspect this is due to a database tables change. I am going to rollback to a earlier version of the database on my local machine and see how the results look.

**Comment by nmsutton** [comment]
@drdiek preliminary results indicate that this is indeed some problem that came from a database change. Rolling back to an earlier database version (from Apr. 2cnd) appears to restore functionality. I will investigate at what date the database started causing this issue.

**Comment by nmsutton** [comment]
@drdiek I found this was from a misformatted fragment_nbyk.csv file I uploaded on April 15th. I have now corrected this and uploaded the new version to Github and phpdev. Please check this and make sure it is completed.

**Comment by drdiek** [comment]
@nmsutton Good work.
