### ISSUE TITLE
GAA: [search]: In Neuron Type search pull-down menu change "Electrophysiology" to "Membrane biophysics"

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#524]
This is apparently more intricate that I originally thought. Some of the uses of "Electrophysiology" in search.php need to be changed, whereas others need to be kept because they refer to a column in one of the database tables. Strictly speaking, we should probably change the column title too, but that may be more involved.

**Comment by drdiek** [comment]
@nmsutton I can't tell whether or not search_engine.php also needs to be modified in some way.

**Comment by nmsutton** [comment]
@drdiek I have added code near lines 643 and 662 that now cause "Membrane Biophysics" to be displayed instead of "Electrophysiology" on the search page and do not change the column name accessed. I have uploaded the code to phpdev and Github. Please review this work and tell me if it is sufficient.
