### ISSUE TITLE
CT: [neurites]: Reading from the wrong column for axonal and dendritic lengths

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#526]
From Carolina: "Nate is still using the wrong column to display the length by parcel (For example HICAP shouldn’t have Ax in H: HIPP should display Ax only in SMo), he should use the values from the column Filtered_Total_length (μm) . Additionally, parcels in CA2 are displayed wrong (CA2 Pyr is showing Ax in SLM)."

I have an inquiry in to Carolina to clarify exactly what the difference is between the two columns.

**Comment by drdiek** [comment]
@nmsutton At my best guess, the location of the problem is line 96 of synap_prob/gen_json/generate_json.php, but I leave it to you as you know your own code best.

**Comment by nmsutton** [comment]
@drdiek I am not quite sure what is being refered to here. A query from lengths with HICAP in the axon cell is:
```
 SELECT CAST(STD(CAST(total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS std_tl, CAST(AVG(CAST(total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg, CAST(AVG(CAST(total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg_trunk, CAST(COUNT(CAST(total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS count_tl FROM neurite_quantified WHERE neurite_quantified.unique_id=1013 AND neurite_quantified.neurite='DG:H:A' AND total_length!='';
```
It seems to me "neurite_quantified.neurite='DG:H:A'" makes it correctly reporting axon values. Also, HICAP has both axon and dendrite values reported, so even if they were flipped "HICAP shouldn’t have Ax" dosen't seem to make sense. You can try to run the same query to test the results created if wanted. Can further clarification please be provided about this?

**Comment by drdiek** [comment]
@nmsutton What is going on here is a little complicated to describe, but I will try. When we first established the neuron type morphology interpretations, we made decisions wherein a certain amount of axons in a layer was at times below a reporting threshold that we had established. When Carolina started to quantify the amount of axons, she simply reported what was in every possible layer. Later, under Giorgio's guidance, we decided that we would still only report axons in layer if the original interpretation had them there. If they weren't in the original interpretation, then the new numbers would be "absorbed" into layers that did meet the interpretation threshold. This all boils down to HICAPs having a trace amount of axons in DG:H, but they are below the original reporting threshold. This is why Carolina has two columns in her spreadsheet: Total_length, which corresponds to the raw values, and Filtered_Total_length, which corresponds to the original interpretation thresholding. The php encoded queries need to access the Filtered_Total_length values to be correct.

**Comment by nmsutton** [comment]
@drdiek ok so to confirm you are saying to replace "total_length" with "filtered_total_length" in the queries?

**Comment by drdiek** [comment]
@nmsutton Yes, that is what I am saying.

**Comment by nmsutton** [comment]
@drdiek I have tried applying the update requested but do not see a difference in results. Here is a query with the new column:
```
 SELECT CAST(STD(CAST(filtered_total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS std_tl, CAST(AVG(CAST(filtered_total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg, CAST(AVG(CAST(filtered_total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg_trunk, CAST(COUNT(CAST(filtered_total_length AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS count_tl FROM neurite_quantified WHERE neurite_quantified.unique_id=1040 AND neurite_quantified.neurite='DG:H:A' AND filtered_total_length!='';
```
If those are the results the database is providing I am unsure if this is an issue with my code, because it seems to be collecting the data from the tables based on Carolina's spreadsheet correctly, do you agree?

**Comment by drdiek** [comment]
@nmsutton If you change the unique_id to 1009 from 1040, then you get NULL values for the A:DG:H, as expected.

**Comment by nmsutton** [comment]
@drdiek ok thanks, sorry for the confusion. I have now added the new version to phpdev and it appears to be working as wanted.

**Comment by nmsutton** [comment]
@drdiek I have also uploaded the corresponding updated adl_values.csv downloadable file.
