### ISSUE TITLE
GAA: [neurites]: Missing figure from axonal length Evidence page

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#530]
From Giorgio: "n some initial spot checking, I found one broken link here:
hippocampome.org/phpdev/attachment/neurites/Ferrante-McCormick-2017-3186-v27-CerebCortex-Fig2D-Cell6017.jpeg
following the evidence of axonal length for EC (e)223111p-CA1_1000-SUB_100 LIII Pyramidal in EC:VI."

As far as the missing figure that Giorgio mentioned, the link is to a .jpeg file, but the correct file name is a .jpg file. The attachment_neurite.csv correctly lists the .jpg file name, so I am not sure why the link is wrong.

**Comment by nmsutton** [comment]
@drdiek I found that the original hco code had a convert jpg to jpeg extension function. I have now disabled that for the synapse probability pages and it appears to have the images showing correctly now. Here is [the example](http://www.hippocampome.org/phpdev/property_page_synpro.php?id_neuron=6017&val_property=EC_VI&color=red&page=1&sp_page=dal) originally listed with the Ferrante-McCormick image now loading. Please review this and close this if it looks completed.

**Comment by drdiek** [comment]
@nmsutton Weird. I have no idea why such a conversion function would exist.
