### ISSUE TITLE
DWW: [neurites] For NxN matrices, the matrix value does not correspond to the Total value in the intermediate Evidence table

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#532]
For Interneuron Specific LMO-O to CA1 Basket CCK+ for the Number of Potential Synapses, the matrix value is 0.008420, but the intermediate table's Total value is 0.005660.

For CA1 Bistratified to CA1 Axo-axonic for the Number of Contacts, the matrix value is 9.88, but the intermediate table Total value is 9.44. Also, the intermediate table is labeled Parcel-Specific Potential Synapses Per Neuron Pair, when it should be labeled Number of Contacts per Neuron Pair.

For CA1 Ivy to CA1 Ivy for the Probability, the matrix value and intermediate table value do not match. Also, the title of the table is wrong, too.

**Comment by nmsutton** [comment]
@drdiek the json files were just out of sync with the latest database content. I recreated all json files and now the values match. I also corrected the titles in the pages. Please review this work and close this if completed.
