### ISSUE TITLE
KM: [synaptome]: Add "4-state Tsodyks and Markram synapse model parameters" to hover over

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#535]
On the synaptome modeling matrix page, add the phrase "4-state Tsodyks and Markram synapse model parameters" to the hover over windows.

**Comment by nmsutton** [comment]
@drdiek I have added this work. Keivan originally said "I suggest using “model parameters” instead, and when the user hovers over it show “4-state Tsodyks and Markram synapse model parameters” and a link to equations we use for modeling or to my simulator’s GitHub page.". The model parameters text now has a hover over describing the 4-state TM and clicking it take the user to the Github page. I never received additional equations but I don't know that they would be needed. Please review this work and if completed please close this.

**Comment by drdiek** [comment]
@nmsutton I am not finding this hover-over information. When and where does it appear exactly? All I see are statistics in a hover-over window.

**Comment by nmsutton** [comment]
@drdiek 
![mp](https://user-images.githubusercontent.com/3514598/86379033-50628800-bc58-11ea-817e-bcc509427b09.png)

**Comment by drdiek** [comment]
@nmsutton OK, thank you for the clarification. For the benefit of users, could you please change the text "Model Parameters:" into a <a href></a> explicit link, while maintaining the hover over?

**Comment by nmsutton** [comment]
@drdiek I added an underline to indicate it is a link, the same as the way the value links are shown in the matrix.
