### ISSUE TITLE
KM: [synaptome]: Add a link to the equations used for modeling to the hover over

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#536]
On the synaptome modeling matrix page, add a link to the equations used for modeling to the hover over window or a link to Keivan's simulator's GitHub page (https://github.com/k1moradi/SynapseModelersWorkshop).

**Comment by nmsutton** [comment]
@drdiek I have added the Github link. You can decide if equations are needed, I never received them, and Keivan wrote that either equations or a Github link is acceptable it seems.
