### ISSUE TITLE
KM: [synaptome]: Use small letters in subscripts in the "Model parameters" pull-down menu

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#537]
For example, 𝜏D -> 𝜏<sub>d</sub>, and G -> g and ...

**Comment by drdiek** [comment]
Keivan commented: "I think you may make a custom select/option menu with DIV like the following tutorial: https://www.w3schools.com/howto/howto_custom_select.asp."

**Comment by drdiek** [comment]
@nmsutton You also need to correct the spelling of Celsius and possibly add a degrees symbol if you are able.

**Comment by nmsutton** [comment]
@drdiek I have completed this work. Please review this and close if completed.
