### ISSUE TITLE
KM: [synaptome]: For the other options menu only the condition itself should be selectable

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#538]
From Keivan: "Currently, the title is selectable as well. I suggest you to put these element in an invisible table having two rows. Put the condition title on the first row and the option menu’s in the second row, and remove the option’s title from option’s themselves. (Note that new names under the recording mode have been suggested)."
![Conditions](https://user-images.githubusercontent.com/4380011/84670443-25580480-aef4-11ea-96f5-28197af177cb.jpg)

**Comment by nmsutton** [comment]
@drdiek I have now added this. Please review and close if complete.
