### ISSUE TITLE
KM: [synaptome]: Merge the "Synapse physiology" and "Synaptic modeling" pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#539]
All the contents of the "Synapse physiology" menu can become a link on the right side of the "Synaptic modeling" page. The "Synaptic modeling" title should change to "Synaptic physiology."

**Comment by nmsutton** [comment]
@drdiek I have added the updates requested here. Please review this and close if complete.

**Comment by drdiek** [comment]
@nmsutton Can you please change the tab title from "Synaptic Parameters" to "Synaptic Physiology"?

**Comment by nmsutton** [comment]
@drdiek nice catch, I have made the correction.

**Comment by drdiek** [comment]
@nmsutton Please change the text in the upper right corner from "Synapse Physiology" to "Source experimental data." Also, please change the text in the upper right corner from "More resources" to "Synaptome." Once these two changes have been made, I will close out this Issue.

**Comment by nmsutton** [comment]
@drdiek changes complete, thanks.
