### ISSUE TITLE
KM: [synaptome]: Re-format the matrix cells to be like the Connectivity matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#541]
From @k1moradi: "White cells should be reserved for cells that are not potential connectivity, red crossed for refuted, black for excitatory (with white text) and grey for inhibitory (with black, or possibly white, text). Then we can show model parameter values in each cell. I also like the height and width of the cells on the Connectivity matrix, which are square."

**Comment by nmsutton** [comment]
@drdiek so far with this I have been able to extract connectivity values of 'negative', 'potential', or 'positive' from the TypeTypeRel table. I have also been able to use that for some color coding of cells. Can you please tell me, is there somewhere in the hippocampome database that describes if a neuron is excitatory or inhibitory? I could use that data for the further color coding requested.

**Comment by drdiek** [comment]
@nmsutton You can access this information in the Type table, in the excit_inhib column. 'e' stands for excitatory and 'i' stands for inhibitory.

**Comment by nmsutton** [comment]
@drdiek I have updated the page to include colors for connectivity details (matching those on the connectivity page) and added a revised legend on the right. Some things that might be nice to work on but I don't know if they are needed are removing white space in the horizontal margins of cells, and making cells smaller. Both of those things I am not sure how to do. Giorgio mentioned wanting the work with Keivan's research done in a week or two. With the progress made on it so far, does it seem reasonable to email Keivan and Giorgio to look at the page and see if they want anything before it is considered the final version?

**Comment by drdiek** [comment]
@nmsutton The white space is a little odd, but not a deal breaker, in my opinion. The size of the cells is fine. Sure, go ahead and solicit their opinions.
