### ISSUE TITLE
GAA: [neurites] Discrepancy between matrix and csv file values

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#544]
From Giorgio: "I’ve just downloaded the CSV file for the numbers of contacts from the dev portal (which is currently what J Neurosci reviewers are looking at…) and cannot reconcile the numbers. For example, the first row (EC LI-II Multipolar-Pyramidal to EC LIII-V Bipolar Pyramidal) has an average of 0.732 (which is already suspicious since I though the minimum should be 1!), but the corresponding entry in the php matrix says 1.46. Moreover, the CSV says there are 2 data points but the links from the matrix points to 3 pieces of evidence."

**Comment by drdiek** [comment]
@nmsutton We spent quite a bit of time refining the equations in php, but perhaps they did not make it over to the generator of the csv file?

I found some php code that seems to be used to generate csv files. So, they are generated on the fly and not pre-populated?

**Comment by nmsutton** [comment]
@drdiek I have now updated the csv file and I uploaded the creation code for the csv files to synap_prob/gen_csv_dls/ in case it is wanted in the future. Please review the csv file to check the completion of this.

**Comment by drdiek** [comment]
@nmsutton I will close this after I talk with Giorgio this afternoon about standard deviations and the number of data points.
