### ISSUE TITLE
DWW: [synaptome] Number of significant digits

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#545]
In the hover-over statistics, the mean value has the correct number of significant digits (4), but the standard deviation value, the lower range value, and the upper range value have too many digits displayed. They should also be limited to 4 significant digits.

**Comment by nmsutton** [comment]
@drdiek I have now made all values have 4 significant digits. Please review this and close if completed.

**Comment by drdiek** [comment]
@nmsutton It is almost perfect. The last little problem that I now see is that the standard deviations cannot be more accurate than the main values. For example, 6.684 ± 0.9453 should become 6.684 ± 0.945 because the main value is only accurate to the third decimal place. Does that make sense?

**Comment by nmsutton** [comment]
@drdiek this one was a bit tricky but I wrote some custom code to do what you requested and it appears to have successfully added the update. Please review this and close if complete.

**Comment by drdiek** [comment]
@nmsutton It appears to work for the g and u values, but not for any of the values for the three tau parameters. There still appears to be one extra digit being displayed for the standard deviations.

**Comment by nmsutton** [comment]
@drdiek can you please reference an example? When I check tau_d with [Rat,M,P14,22,VC] Granule-Hilar Ectopic Granule appears to successfully remove an extra digit from CV, and others I have checked appear to do the same. I would guess this would be the same for STD, but will be interested in any examples you provide that are contrary to that.

**Comment by drdiek** [comment]
@nmsutton Try tau_r, for DG Granule to DG Axo-axonic:

![Screen Shot 2020-07-03 at 12 24 44](https://user-images.githubusercontent.com/4380011/86486083-63dd2400-bd28-11ea-9d38-d9707af77ff5.jpg)

**Comment by nmsutton** [comment]
@drdiek thanks for the example. Just to clarify, you want the number of decimal places of all values to match the main value, correct?

**Comment by drdiek** [comment]
@nmsutton Yes, exactly.

**Comment by nmsutton** [comment]
@drdiek I have written new custom code to finish this task and it appears the work has been completed with this. Please review this and close if complete.
