### ISSUE TITLE
GAA: [neurites]: Missing Evidence figures

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#546]
From Giorgio: "Just noticed in the evidence for CA1 bistratified dendritic length in SO that the first entry is missing the figure and the segmentation evidence file."

@nmsutton I checked the attachments folder and the files exist, and I checked the attachment_neurite.csv file and the entries are there, so I do not understand why the above mentioned figures are not appearing.

**Comment by drdiek** [comment]
@nmsutton I found the source of the error. The entries in the spreadsheet and the file names are all tagged with the incorrect Unique ID. It should be 4080, not 4079. I will let you know once I have corrected everything, and then you will need to perform a new ingest for the website to be fixed.

**Comment by drdiek** [comment]
@nmsutton I have fixed the spreadsheet and renamed all of the appropriate figure files, so everything is ready for you to perform a new ingest into the database, which should solve the missing figures problem.

**Comment by nmsutton** [comment]
@drdiek I performed a new ingest and now the issue appears fixed. Thanks again for your work on this.
