### ISSUE TITLE
GAA: [neurites] Add hover-over windows to intermediate NxN tables

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#549]
For the intermediate tables for the NxN matrices, please add hover-over windows to the parcel-specific entries. Each window should display the mean and the standard deviation for the given parcel. If possible, a similar hover-over window should be placed over the Total value, too.

**Comment by nmsutton** [comment]
@drdiek I have added this work. One note is that adding a hover-over to the total needs it to be a link (from what I am aware of) when previously it was not a link. The link simply refreshes the page, and I made the link color black to indicate that it is different than the others that go to an evidence page. Please review this work and see if it is complete.
