### ISSUE TITLE
GAA: [supertype] Change the Supertype of CA3 Mossy Fiber-Associated cells to be L-targeting

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#558]

**Comment by drdiek** [comment]
@nmsutton If you could please re-ingest the morphdata.csv file, then this change would be propagated to the database.

**Comment by nmsutton** [comment]
@drdiek in csv2db_import morphdata.csv shows it was last updated 5 months ago, is a new update needed before rebuilding the db?

**Comment by nmsutton** [comment]
@drdiek I have rebuilt the database and uploaded it to phpdev (with the latest csv2db_import repo files) since you posted this issue, but please share, does morphdata.csv need to be updated in the csv2db_import repo?

**Comment by drdiek** [comment]
@nmsutton My apologies for being so slow on this. Yes, morphdata.csv does need to be updated, and I have just done so.

**Comment by nmsutton** [comment]
@drdiek no problem, I rebuilt the db so the update should be live now.
