### ISSUE TITLE
DWW: [phases] Create the main phases matrix with values

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#559]
<img width="555" alt="phases_mockup" src="https://user-images.githubusercontent.com/4380011/95769643-34727780-0c86-11eb-97b4-c0efaaa71a48.png">

**Comment by nmsutton** [comment]
@drdiek I made some updates to csv2db and so far I have been able to successfully get the 3 phase tables imported into the db. One thing to note is that in phases.csv I changed the column title "PMID" to "PMID_or_ISBN" to match the map.py import code. Please update your copy of phases.csv to have the different column name.

**Comment by drdiek** [comment]
@nmsutton Do you mean you changed "PMID" to "PMID/ISBN" or "PMID" to "PMID_or_ISBN"?

**Comment by nmsutton** [comment]
@drdiek I meant "PMID" to "PMID_or_ISBN" in the phases.csv column titles.

**Comment by nmsutton** [comment]
@drdiek Please tell me, where is the data for the "other" column on the main matrix?

**Comment by drdiek** [comment]
@nmsutton To be honest, I had not thought this part out very well. There are three possible sources for "other" in the phases table: highest priority is "ripple," which would be labeled as "Ripple" in the matrix, if such a value exists for the neuron type; second priority would be "gamma," which would be labeled as "Gamma" in the matrix, if such a value exists for the neuron type; and lastly would be "epsilon," which would be labeled as "Epsilon" in the matrix, if such a value exists for the neuron type. If none of these three exists, then the matrix cell would be left blank.

**Comment by nmsutton** [comment]
@drdiek ok, I can imagine how to program that. I assume whatever value (ripple,gamma,epsilon,none) is present for the lowest ranking entry in the metadataRank column is the one that instructs what value to include in the "other" column, correct? Other ranked entries are ignored?

**Comment by drdiek** [comment]
@nmsutton Yes, you have it correct. I forgot about run_stop_ratio, which should display "Run/stop ratio" and should be ranked in between gamma and epsilon.

**Comment by nmsutton** [comment]
@drdiek thanks. Given a neuron class, if "theta" has a value with a low rank, e.g., 4, and the lowest rank "swr_ratio" has a value is 6, should no value be reported for swr_ratio, to match the results from the conditions that were present for "theta"? Alternatively, should swr_ratio report the value that has the lowest rank even if different conditions than theta are used for it (and different conditions would be reported in the hover-over for each value)? Since there will be checkboxes for the conditions's parameters (e.g., animal, age), I would be a bit confused about how to show that if "select preferred" was checked off. I assume the checkboxes direct what options will be available for selection of conditions (with the lowest rank given those options).

**Comment by drdiek** [comment]
@nmsutton I guess I am picturing the following: for a given set of checkboxes, you display the lowest ranked theta and swr_ratio values that meet the conditions of the check boxes. This could mean that the conditions for theta could differ from the conditions for swr_ratio, as long as both sets of conditions conform to the check boxes.
Select preferred would check only those boxes that correspond to the lowest ranked set of conditions.

**Comment by nmsutton** [comment]
@drdiek ok, I will build that. One thing is that, if swr_ratio and theta have different conditions, should "select preferred" be a combination of all conditions between the lowest rank of each? For example, if lowest rank theta has one animal, and lowest rank swr_ratio has another, than the checkboxes would include both animals when "select preferred" is selected? It seems this would conform to the idea of the check boxes representing constraints on the options for both theta and swr_ratio.

**Comment by nmsutton** [comment]
@drdiek I have now created an initial version of the matrix: http://www.hippocampome.org/phpdev/phases.php .

**Comment by drdiek** [comment]
@nmsutton It is looking good. I have just a couple of suggestions for the hover-over windows. Instead of "unknown," can we use the phrase "unknown sex" instead? Rather than the full phrasing from the column "recordingAssignment," I would rather that we use simpler phrases such as "whole-cell patch clamp" or "juxtacellular." What would be the simplest way of achieving this? Should I add a new column to the phases.csv file?

**Comment by nmsutton** [comment]
@drdiek I will update the "unknown" description in the checkbox. Given the number of entries in the phases table is 385 I think it would be reasonable to have an additional column with the shortform description of the recordingAssignment. This can help make sure the checkbox selection matches the right vocabulary, and that the vocabulary presented is more accurate than pattern matching to be safe. Please tell me, would it be acceptable if you created that additional column?

**Comment by drdiek** [comment]
@nmsutton Yes, I will create the new column.

**Comment by drdiek** [comment]
@nmsutton OK, I have added a new column for the recording method. I have also added new columns that describe the various error types, such as SD or SEM. I have updated map.py and models.py to accommodate the new columns.

**Comment by nmsutton** [comment]
@drdiek thanks, please tell me how do the age entries in the phases table translate into (adult, young adult, not reported) options?

**Comment by drdiek** [comment]
@nmsutton I have now added a new Age_type column to the phases.csv file and added the ageType variable to the map.py and models.py files.

**Comment by nmsutton** [comment]
@drdiek I have added all the functionality that I can now to the site. There are several open questions about how to design the site and I have included them in a open questions section at the bottom of our shared project doc (that I shared in the email with the subject "phase locking of neuron types"). I can not move forward to complete this work without answers to those questions, so I request that you please help answer them.

**Comment by nmsutton** [comment]
@drdiek thanks for providing the answers. Posted some follow-up questions and two additional questions.

**Comment by nmsutton** [comment]
@drdiek thanks again, I added new follow up questions to Q 1+2 and a response to 6.

**Comment by nmsutton** [comment]
@drdiek I added two follow up question in Q1 and Q2.

**Comment by drdiek** [comment]
@nmsutton I made an error in the theta description. The word "trough" should instead be "peak."

Also, can you please modify the column title for Theta such that it reads "Theta (deg)," which is to distinguish the values from radians.

**Comment by nmsutton** [comment]
@drdiek I have made the updates. Also, 1 more follow up question added to Q1 and I made a comment on Q2.

**Comment by drdiek** [comment]
@nmsutton What exactly is the "select preferred" button programmed to do, because when I activate it, after clearing all of the buttons, nothing appears to be selected, so nothing shows up. Also, when I clear all buttons, some of the "Other" cells still are filled.

**Comment by nmsutton** [comment]
@drdiek the other cells appearing after all checkboxes were cleared was a bug in the sql code and I have now resolved that. "select preferred" was not originally intended to be used when the check boxes were all cleared, but I will work on including a way to make that an option. Starting with all boxes checked, selecting a row, selecting "select preferred", then pressing "update" returns only check boxes checked that match the lowest ranked theta and swr_ratio conditions for that row.

**Comment by drdiek** [comment]
@nmsutton OK, that is not quite what I had in mind, but I was not explicit enough in my desires for that check box. I was picturing selecting "select preferred" and getting all of the preferred check boxes checked, i.e. rats, adult, male + female, sharp pipette, and freely moving. Would this be possible? Perhaps the button should be relabeled as "select most preferred conditions" or something to that effect.

**Comment by nmsutton** [comment]
@drdiek if I understand accurately, you are saying that a user:
Selects a neuron's row.
Clicks "select most preferred conditions" and update.
Then all of the preferred check boxes for that neuron's values become checked and all non-preferred ones are unchecked.
Correct?

**Comment by drdiek** [comment]
@nmsutton I was not imagining the user selecting a row first. I was imagining clicking on "select most preferred conditions" and updating, then all of the preferred check boxes are selected and the entire table gets updated with those values that correspond to the absolutely most preferred conditions possible. I think the check boxes should always affect the entire matrix and not just row by row.

**Comment by nmsutton** [comment]
@drdiek I have added to the site the function where if "select most preferred conditions" is selected and update is pressed then only the conditions that create the lowest ranking values for the whole matrix are checked. Does this look correct?

**Comment by drdiek** [comment]
@nmsutton Can you please move the "select most preferred conditions" checkbox above the "select all" checkbox and display the entire tag on one line? You will need to change the hover-over window for this checkbox, too.

**Comment by nmsutton** [comment]
@drdiek I have applied the requested updates. Does work on the matrix page now appear complete?

**Comment by drdiek** [comment]
@nmsutton Just a last few minor changes. Can you please update the "not reported" checkbox to read "age not reported" and make sure that entire new phrase is what shows up in the hover-over window? Also, can you please update the phrase "unknown" to "unknown sex" in the hover-over window?

**Comment by nmsutton** [comment]
@drdiek I have created the updates.

**Comment by drdiek** [comment]
@nmsutton The hover-ver window information does not appear to be updated. With all boxes checked, the Theta values for CA3 Pyramidal cells still says just "unknown" and not "unknown sex" in the hover-over window.

**Comment by nmsutton** [comment]
@drdiek I updated it so it should be appearing as wanted in the matrix.
