### ISSUE TITLE
DWW: [phases] Add hover-over windows to the phases matrix values

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#560]
<img width="555" alt="phases_mockup" src="https://user-images.githubusercontent.com/4380011/95769533-0a20ba00-0c86-11eb-92a8-a318baa3f324.png">

**Comment by nmsutton** [comment]
@drdiek I have created the hover-overs

**Comment by nmsutton** [comment]
@drdiek please check if this is completed now.
