### ISSUE TITLE
DWW: [phases] Add the check boxes to the main phases matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#561]
<img width="555" alt="phases_mockup" src="https://user-images.githubusercontent.com/4380011/95769533-0a20ba00-0c86-11eb-92a8-a318baa3f324.png">

**Comment by nmsutton** [comment]
@drdiek I created the checkboxes but they do not yet update the values. I created a value update test where clicking the update button changes the first theta value. I will use that same method to make the check box selection able to update values.

**Comment by nmsutton** [comment]
@drdiek the checkboxes are now working. The "select preferred" checkbox works by selecting a matrix row before or after checking that checkbox, then clicking update.

**Comment by nmsutton** [comment]
@drdiek please check if this is completed now.
