### ISSUE TITLE
[neurites] SD min and max values discrepency

### ISSUE THREAD

**Issue by nmsutton** [Hippocampome-Org/php#562]
Given an example neuron class, CA1 Radiatum Giant (4054), and neurite, CA1:SR:D:
The csv d/l file calculates SD min and max as:
MIN(avg_path_length), MAX(avg_path_length) resulting in (98.0, 320.56)
and the main matrix calculates it as:
MIN(min_path_length), MAX(max_path_length) resulting in (0.0, 641.11)
It does not make sense that a path length could be 0, correct?
The data for min_path_length is all 0.0 given this example, as found in the query:
SELECT * FROM neurite_quantified WHERE unique_ID=4054 and neurite='CA1:SR:D';
Is this an error in the neurite_quantified data, avg_path_length should be used, or 0.0 is correct?
We need to figure this out because these are values report in fig 8.

**Comment by drdiek** [comment]
@nmsutton When the neurite, either axon or dendrite, is located in the same layer as the soma, then the minimum path length is recorded as zero, according to the description Carolina wrote in the manuscript. Therefore, this is not a mistake.

**Comment by nmsutton** [comment]
@drdiek ok thanks, so MIN(min_path_length), MAX(max_path_length) is the correct code for min and max?

**Comment by drdiek** [comment]
@nmsutton Yes, i would go with MIN(min_path_length), MAX(max_path_length).

**Comment by nmsutton** [comment]
@drdiek thanks! This issue is complete in that case.
