### ISSUE TITLE
DWW: [marker]: Update the markers for DG Granule, DG Mossy, CA2 PC, CA1 Superficial PC, and CA1 Deep PC

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#563]
-Granule cells and mossy cells: both PCP4+ and GluA2/3+ (Fig.3H)

-CA2 pyramidal cells: CB- (currently is Positive-Negative(subtypes) but NO PCP4+ cell in CA2 is + to CB. We show in Fernandez-Lamo those CB+ neurons in CA2 are actually CA1 pyramidal cells. (Updated Sup.Fig.2)

-CA1 pyramidal cells: superficial are CB+; deep are CB-; please add Wfs1 as a dorsal CA1 marker (Fernandez-Lamo et al,  
https://pubmed.ncbi.nlm.nih.gov/30759386/

**Comment by drdiek** [comment]
@nmsutton I could really use your advice with this task. I am trying to add a new marker, Wfs1, to the main markers matrix. However, I have been unable to discern how to make that happen. I have added the marker to the explicit listings in markers.php, markers_search.php, getMarkers.php, function/markers/marker_helper.php, and even to csv2db/lib/markerdata_string_field.py. All of these modifications have succeeded in getting the new marker into the database, because one can search for it with the Neuron Type search. It even shows up in the listing on the Neuron pages for CA1 Superficial Pyramidal and CA1 Deep Pyramidal cells, but, unlike the other markers listed, it is not clickable for some reason. I do not expect for you to do the work for me, but do you have any suggestions for where I might try to make further modifications? As far as I can tell, the original coding of the first set of main matrices, is rather arcane compared to the coding for the more recent matrices. I do not think the original matrices were coded in such a way that anticipated expansions of the matrices. Any suggestions would be greatly appreciated.

**Comment by nmsutton** [comment]
@drdiek I am pretty busy now but I should be able to take a look at this Thurs afternoon.

**Comment by drdiek** [comment]
@nmsutton I have gotten the new marker, Wfs1, to show up properly linked on the Neuron page for CA1 Superficial Pyramidal and CA1 Deep Pyramidal on devur3. I can also see the definition page for Wfs1 by typing in the address "hippocampome.org/devur3/neuron_by_marker.php?marker=Wfs1". The main markers matrix is currently not displaying. Instead I get an error that reads "Length of colNames <> colModel!" colModel is hand coded in markers.php, so that seems straightforward, but I am unsure how colNames in markers.php gets populated, so I am having trouble debugging this error.

**Comment by drdiek** [comment]
@nmsutton The marker matrix flags are all showing up as expected. What is wrong now is that some of the column names are missing, and those that are appearing are being printed horizontally rather than vertically.

**Comment by nmsutton** [comment]
@drdiek I made some progress on the column names, but I see you just uploaded an update to github also. I found that if a line:
`let $n_columns=24;`
is added to markers.php on line 540 than the column names appear to show up with the intended rotation. I will check what occurs when I try to load your latest files from github also.

**Comment by nmsutton** [comment]
@drdiek I have found that when n_columns is set to 102 and Wfs1 and Y2 are added to the markers with the code on github before your latest commit where you removed that, then the new marker columns show up with the correctly rotated column headings. Isn't that what was wanted?

**Comment by drdiek** [comment]
@nmsutton Great, thank you. Obviously I still do not understand some of the nuances of programming in php. The file getMarkers.php includes the file /function/markers/marker_helper.php, where the variable $n_markers is defined for use later in getMarkers.php. I tried to define a variable $n_columns in marker_helper.php and then include that in markers.php, in order to remove the multiple instances of hard-coded values, but that did not seem to work. However, this leaves me still more confused, as I rewrote some of the code in markers.php to use $n_markers, rather than having to hard code the number of markers in multiple locations, and that code seems to be working.

**Comment by drdiek** [comment]
@nmsutton Now I am really confused. I just uploaded the same database and the same markers files to devur2 that are on devur3, and everything is working on devur3, but I get an error on devur2, which complains that there is a discrepancy between the size of two variables, colModel and colNames.

**Comment by drdiek** [comment]
@nmsutton OK, it turns out that I had not cleared the json cache file, which was causing the problem. All is now functioning as expected.
