### ISSUE TITLE
DWW: [morphology] Formally split CA1 PCs into Superficial and Deep neuron types

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#564]

**Comment by nmsutton** [comment]
@drdiek unfortunately with your latest update to morph_fragment.csv related to this I am now getting the following error when I try to build the db:
begin... [10] /home/hdb/AscoliLab/github/csv2db_import/static/csv2db/dat/morph_fragment.csv
CommandError: Failed to load table(s)
That error seems to be one that occurs if the csv file's data is not formatted correctly for import. When I run the db build using the morph_fragment.csv file in csv2db before the latest commit, it works without issues.

**Comment by drdiek** [comment]
@nmsutton I restored the version of morph_fragment.csv and double checked the update to morphdata.csv, so everything should be ready for import.

**Comment by nmsutton** [comment]
@drdiek I was successfully able to build the database with the lastest csv2db github files. I have uploaded the new db to phpdev. I refer to you to see if this has completed the intended update.

**Comment by drdiek** [comment]
@nmsutton I do not understand how our original database was set up. I thought I changed all of the necessary morphology files to split the CA1 Pyramidal cells into Superficial and Deep sub-types, but nothing seems to have changed in the database.

**Comment by nmsutton** [comment]
@drdiek it appears I rebuilt the database before your latest csv2db commit described as "...accommodate Superficial and Deep CA1 PCs". I will rebuild it again with that update to see if it creates the update wanted.

**Comment by nmsutton** [comment]
@drdiek I successfully rebuilt the database including the latest update that you made today. Please take a look and see if this added the content that is wanted for this issue.

**Comment by drdiek** [comment]
@nmsutton There is still not a lot of change in the database, but I needed to updated another file, which I had overlooked before. Can you please rebuild one more time?

**Comment by nmsutton** [comment]
@drdiek when I try to rebuild it with the latest files it unfortunately has the same type of error with morph_fragment.csv that occurred previously: static/csv2db/dat/morph_fragment.csv CommandError: Failed to load table(s)

**Comment by drdiek** [comment]
@nmsutton My guess is that the accented characters in some of the authors' names were causing the trouble. I think I have removed them all. Does the error message also relay a line number of the failure or perhaps some context to help track down the problems?

**Comment by nmsutton** [comment]
@drdiek it unfortunately does not provide more details. I will rebuild it again with your update to csv2db.

**Comment by nmsutton** [comment]
@drdiek I tried to rebuild it with the latest csv2db files but morph_fragment.csv is still not importing. The only error information it provides is this:
2020-10-28 2:50:14 begin... [10] home/hdb/AscoliLab/github/csv2db_import/static/csv2db/dat/morph_fragment.csv
CommandError: Failed to load table(s)

**Comment by drdiek** [comment]
@nmsutton OK, this time I searched through the quotations for strange characters and removed them.

**Comment by nmsutton** [comment]
@drdiek I am still getting the same error unfortunately.

**Comment by drdiek** [comment]
@nmsutton I restored morph_fragment.csv, so it should work again. Updating the original 122 neuron types apparently is non-trivial.

**Comment by nmsutton** [comment]
@drdiek I have rebuilt the db with your latest update restoring morph_fragment.csv and it is live now on phpdev. A suggestion is that if you want to try to get csv2db rebuilding working on your machine, I suggest creating a VM for it and the one I got working uses Ubuntu 16.04.6 LTS. I am also fine with continuing to rebuild the db upon request. That certain version of Ubuntu is close to the version the the current version of hippocampome.org was built on it seems, and it helps with software compatibility compared to newer OSes. It is unfortunate the VM I created was not able to run on your machine, but this might be another option if you want a faster turn around time on testing such rebuilds. That said, I am ok with continuing to rebuild it when you would like me to.

**Comment by drdiek** [comment]
@nmsutton I managed to get Ubuntu running, but I need to load Django somehow. I tried again loading the VM you created and it finally worked after I downloaded the latest version of VirtualBox and tried some tweaks I found online. I am now stuch trying to clone from GitHub because I am unable to log in. I am wondering whether it has something to do with the fact that I have activated two-factor authentication on my GitHub account, and it is somehow running interference.

**Comment by drdiek** [comment]
@nmsutton Some of the morphology changes are getting through. When I click on squares in the morphology matrix, the Evidence pages for cell ID 4000 are missing, and so is the Neuron page for 4000. However, the Neuron pages for 4098 and 4099 do show up, so the information is somewhere in the database. I still need to figure out how to change the appearance of the morphology matrix such that 4098 and 4099 show up instead of 4000.

**Comment by drdiek** [comment]
@nmsutton Yay! I managed to finally get the import to run natively on my Mac. I had to generate a SECRET KEY and I had to copy the settings.py file to another directory, but it finally works.

**Comment by nmsutton** [comment]
@drdiek I am glad to hear that! Is it running for you on the Mac with or without the VM?

**Comment by drdiek** [comment]
@nmsutton Without the VM.

**Comment by drdiek** [comment]
@nmsutton Oh, yeah, I forgot to mention that I also finally discovered that user.csv was missing from the collection of .csv files, which was a cause of some of my suffering.

**Comment by nmsutton** [comment]
@drdiek Sounds good and I am pleased to hear about you getting it to work. A note is that user.csv is intentionally not included in the csv2db repo because it contains codes to permit private access to the site's dev pages. In the instructions for building the db, in readme.md's database access section, it describes renaming example_user.csv and renaming example_settings.py as well as setting the secret_key variable. I hope getting the site running goes well, let me know if you need any help.

**Comment by drdiek** [comment]
@nmsutton I had been forgetting to clear the cache to see the updated matrix.
