### ISSUE TITLE
[phases] create oscillation phases section of neuron page

### ISSUE THREAD

**Issue by nmsutton** [Hippocampome-Org/php#572]

**Comment by nmsutton** [comment]
@drdiek I created this addition at the bottom of the neuron page ([example link](http://www.hippocampome.org/phpdev/neuron_page.php?id=2000)). Please review this work to see if it is completed.

**Comment by drdiek** [comment]
@nmsutton Please change the section title to "Oscillation Phase Locking." I would also make the Theta (deg) and Theta range values be links to the Evidence page, so you don't need the explicit "Oscillation phases evidence page" link.

**Comment by nmsutton** [comment]
@drdiek I have made the updates. Also, I made the values all have the link, to help with visibility of the link. Is that fine?

**Comment by drdiek** [comment]
@nmsutton I would not link the number of measurements or the representative selection, just the phase values. I might also change the column title "Measurement" to be "Category" instead.

**Comment by nmsutton** [comment]
@drdiek ok, I have made the updates. The only values with links are ones that are not the number of measurements or the representative selection.
