### ISSUE TITLE
DWW: [phases]: Add in vivo firing rates to the phases matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#574]
@nmsutton I would like to add a new column to the phases matrix: "In vivo firing rate (Hz)." This should appear after "SWR ratio" and before "Other." I have added a new column to the phases table: "Firing Rate Rank." You should select a firing rate the same as with the other matrix values by finding the lowest metadata ranked value based on the check boxes. If there are multiple selections to choose from for a given metadata rank, then use the Firing Rate Rank to select from among the remaining possibilities.

**Comment by nmsutton** [comment]
@drdiek I am getting an error when I try to build the db with your change to phases.csv. It is:
2020-10-30 04:26:13.959166 begin... [48] /home/hdb/AscoliLab/github/csv2db_import/static/csv2db/dat/phases.csv
'Firing Rate Rank'

**Comment by drdiek** [comment]
@nmsutton Sorry, an oversight on my part. I have now added the column to phases.csv.

**Comment by nmsutton** [comment]
@drdiek I have added this and it is live on devur2. Please review the work to see if it is completed.

**Comment by drdiek** [comment]
@nmsutton Can you please make the column title appear over two lines, so it fits in the box? I would put "In vivo" on one line and "firing rate (Hz)" on the second line.

**Comment by nmsutton** [comment]
@drdiek I have made the update. In your latest commit to csv2db the Firing Rate Rank column was removed. Can you please add that back in along with any adjustments needed for it due to the neuron types splitting? Also, please review if the work on this issue is completed.
