### ISSUE TITLE
NS: [phases]: Add evidence page

### ISSUE THREAD

**Issue by nmsutton** [Hippocampome-Org/php#577]
Create evidence pages for the phases matrix

**Comment by nmsutton** [comment]
@drdiek It was a tricky process but I got the evidence pages returning articles now. Are figures available for on the cng server for displaying with the article? Otherwise, do new figures need to be uploaded? What other statistics are wanted to be displayed with the article entries?

**Comment by drdiek** [comment]
@nmsutton Looks good so far. At the top, in the Neuron Type section, please add a third line which describes the property being displayed, such as Theta (deg), SWR Ratio, etc. The citations should include the actual value of Theta, or whatever property. The citations should also include the associated protocol metadata, as is already being displayed in the main matrix hover-over windows. I will work on getting the figures together.

**Comment by nmsutton** [comment]
@drdiek I have added property sections for theta, swr_ratio, firing_rate, and other. Each evidence entry (fragment) has its own referenceID; that is needed to track what values in the phases table match that referenceID. Currently, in the phases table the referenceID is missing for the majority of rows. I have, therefore, not made the property sections specific to the referenceID, but instead the cellID. I assume this is not correct, unless told otherwise, but can not make the entries specific to referenceIDs until the referenceIDs are included in the phases table. I do not know how to add them myself because I don't see a unique set of attributes in the phases table that maps each phases table row to a referenceID in the phases_reference table. 
Do we want to report values specific to referenceIDs that represent the fragments? If so, can you please add the referenceIDs to the phases table? I'd be willing to help, but you would need to tell me how, because I don't know a way to further help currently.

**Comment by drdiek** [comment]
@nmsutton I am actively adding the reference IDs. It may take a day or two.

**Comment by nmsutton** [comment]
@drdiek sounds good. I would like to confirm, all lowest ranked values instead of only the median should be listed on the evidence pages, correct?

**Comment by drdiek** [comment]
@nmsutton Actually, I think that the median gets displayed in the main matrix, but all of the values should be listed on the Evidence page, not just the lowest ranked values.

I have finished adding all of the reference IDs. I have also loaded a number of figure files to devur2/attachment/phases.

**Comment by nmsutton** [comment]
@drdiek thanks for the clarification and your work on the referenceIDs and figures. When I looked into the new additions, I found that several values are still missing referenceIDs that connect them to fragments. For example, for cellID 2000:
`SELECT count(*) FROM phases where cellID = 2000 and theta != "";`
`256`
`SELECT count(*) FROM phases where cellID = 2000 and theta != "" and referenceID != "";`
`11`
Since we are intending to display all values that match a cellID on the evidence page, how should values with no fragment (article) associated with them (because no referenceID is listed for them) be displayed? Should a separate section with no article listed and values displayed be included on the evidence page? Please share, since you said you added all of the referenceIDs, there is no way to obtain the referenceID for those other values?

**Comment by drdiek** [comment]
@nmsutton I will investigate. I thought I had made ref ID entries for everything.

**Comment by drdiek** [comment]
@nmsutton It turns out to be a major cutting and pasting error on my part. It will take a bit of time to re-ingest everything. I will let you know when I am finished.

**Comment by drdiek** [comment]
@nmsutton When one opens the Evidence, two problems occur. One, whichever citations is opened, all of the citations that are listed after it disappear. Two, when one opens a citation, the quoted information is duplicated.

**Comment by nmsutton** [comment]
@drdiek I have resolved the citations disappearing issue. 

For the duplication issue, please take a close look at each "Page location" value. Once the reference ids are available in the phases table, the phase values will be specific to each reference id and therefore page location value. The fragments will appear more as different entries, even though their quotes may be the same. I predict the quotes are not actually duplicated, just that different page locations have the same quote because of referencing different parts of the same figure, etc. If you can find an example of non-different page locations but the same quote, or page locations that are suppose to have different quotes, please share. Otherwise, it seems to me the quotes are not actually duplicated, and that each fragment entry will look significantly different once the reference ids are available.

**Comment by nmsutton** [comment]
@drdiek I have now added the retrieve value by reference id process. It is live on the devur2 site. I ran some tests and it appears to be working successfully. Please check if work on this issue is completed now.

**Comment by drdiek** [comment]
@nmsutton This seems to be working. My one critique is that when I click on a Theta value in the main matrix, I am presented with an Evidence page that shows me more than just the Theta evidence. I seem to be presented with all the evidence for a particular neuron type, rather than the specific evidence I was expecting.

**Comment by nmsutton** [comment]
@drdiek it was pretty complicated, but I added filtering of the values on the evidence page based on what was clicked in the main matrix in the way you described. I also added a checkbox on the top left of the evidence page that allows users to toggle between displaying all evidence values or only the type clicked on in the main matrix. Please review the work on this issue to see if it is complete.

**Comment by drdiek** [comment]
@nmsutton I am curious as to why you decided to add this extra functionality that does not exist on any of the other Evidence pages for any of the other Hippocampome attributes? For membrane biophysics, for example, when you look at the evidence for Rin, all you are presented is the evidence for Rin. That particular attribute even gets formally listed at the top of the page in the "Neuron Type" section.

**Comment by drdiek** [comment]
@nmsutton I am curious as to why you decided to add this extra functionality that does not exist on any other Evidence page for any other Hippocampome.org attribute? I take some responsibility here for not being more explicit in my expectations. For example, for membrane biophysics, when you look at the Evidence page for Rin, all you are presented with is evidence for Rin. Rin is even formally listed at the top of the page under the "Neuron Type" section.

**Comment by nmsutton** [comment]
@drdiek sounds like the toggle is unwanted so I removed it. I added it because that functionality was generally already present in the code, so it was relatively easy to include it. In comparison, getting the values showing up on an individual value type basis was the tricky part. The page is now set to only display them in the individual type way. I also added a description of the value type being displayed under the neuron type description at the top of the page, similar to other Evi. pages.

**Comment by drdiek** [comment]
@nmsutton I am sorry it was so difficult. I had not expected that, as it has been done before, and I thought we had enough data in the database to make extracting the necessary information straightforward.

How is the bibliographic information derived? I notice that for CA3 Pyramidal cells for SWR ratio, the authors' list is missing for Tukker et al., 2013. Should I make a separate ticket for this?

**Comment by nmsutton** [comment]
@drdiek thanks, it is understandable that it was not expected to be difficult. My intention in mentioning it is simply to communicate the time I spend on this work compared to my other projects, rather than any other reason. I found that the authors info appears to be retrieved from the phases_fragment table and in that table the authors info is missing. It appears the missing authors info is in rows with ids 47-55. Should the missing info appear once it is added to the table, it seems to me we should also make sure the relevant info is included in other phases_fragment table rows to avoid missing info being shown in the evi. pages. Here is a specific query that relates to the missing info:
`SELECT id, referenceID, cellID, location_in_reference, FTQ_ID, material_used, phase_parameter, phase_parameter_ID, authors, title, journal, year, PMID, pmid_isbn_page FROM phases_fragment WHERE id = '47'`

**Comment by drdiek** [comment]
@nmsutton Thank you for the description. I always thought that the authorship and other bibliographic information would come from the authors table, which is why I have tried to keep that up-to-date.

**Comment by nmsutton** [comment]
@drdiek you're welcome. At a quick look at the code, I'm not sure right away how to reprogram it to use the articles table, but I can look into it further if it seems like it would take an unwanted amount of time to populate the phases_fragment table. Would you prefer I look further into how to reprogram it, or does it seem like populating it would be acceptably quick?

**Comment by drdiek** [comment]
@nmsutton I can populate the phases_fragment table. One difficulty I foresee is the missing entries, which correspond to the new data from the recently submitted manuscript. As the manuscript is only submitted, it does not have a proper PMID or page numbers assigned to it as yet, which apparently makes it hard to reference from the database. I had hoped that assigning it a PMID of 00000000 would work, but apparently it does not. Do you have any ideas as to what to do differently so that these new data will appear?

**Comment by nmsutton** [comment]
@drdiek thanks for the help; I appreciate it. I noticed that row 1 in the Article table also has a pmid of 0. Perhaps there was a collision with that when you tried to set a PMID of 00000000. As you mentioned, it will need a first_page value also. Pubmed does not currently have an article with id 99999999. If you want a unique PMID, one that will not be confused with an existing Pubmed article, that could be a placeholder for an id before we get a real one. There will need to be an addition to the Article table with the new article using the 99999999 id, and that PMID will need to be included in all phases table rows that reference the article, e.g., phases_fragment. Let me know if you need help rebuilding the db with the updates, I don't recall if your system is building csv2db currently.

**Comment by drdiek** [comment]
@nmsutton I was also thinking of using 99999999 just now. It will take some time to replace all of the instances of 00000000 with 99999999 in the various phases spreadsheets. I will let you know when I am done.

**Comment by drdiek** [comment]
@nmsutton OK, something went horribly wrong. The main matrix is only listing 1 value according to the hover-over window for Theta for DG Granule cells. According to the phases_fragment.csv spreadsheet, there should be 6 citation values for Theta for DG Granule cells. The Evidence page lists only 2 citations, although, when you open the evidence, one of the citations is actually a mixture of 2 separate citations. I backed up the database before I updated it, so I can easily reload your last version.

**Comment by nmsutton** [comment]
@drdiek unfortunate it didn't work yet but glad to hear you caught the issue quickly. On a related note, since journal reviewers may be currently reviewing the site, do you have a way to test changes on your local machine before uploading them? If not I could set up a very basic devur3 for testing perhaps if needed. Thanks for your efforts with this.

**Comment by drdiek** [comment]
@nmsutton My machine is completely broken at the moment when it comes to trying to run a local version of the portal. I have no idea at the moment how to fix it. Therefore, a devur3 site would be much appreciated.

**Comment by nmsutton** [comment]
@drdiek sad to hear about the machine, but it looks like I got devur3 up and running now. I copied everything from devur2 into it. I created a new db hippodevur3 and imported my most recent csv2db build into it, and set devur3 to use it. Please try using devur3 for testing your new work before deploying into devur2 and tell me if any issues come up.

**Comment by drdiek** [comment]
@nmsutton One problem I have uncovered has to do with the 16-digit Reference IDs. In the phases.csv file, I have them placed inside of double quotation marks, which preserves all 16 digits. In phases_fragment.csv and attachment_phases.csv, the Reference IDs are not inside of quotation marks, and I notice that the last 2 digits appear to be simply zeros. I tried placing the Reference IDs inside of quotation marks for these two files, but your php code appears to be unable to read the IDs then. What would be your best solution to this situation?

**Comment by nmsutton** [comment]
@drdiek I am a bit confused about what the issue is you are describing. If the last 2 digits are zeros I don't know why any code would process that differently than any other numbers. Can you please provide an example of a RefID causing an issue, and what the issue is that it causes?

**Comment by drdiek** [comment]
@nmsutton By having the last 2 digits be always zeros, that removes some of the discriminatory power of the Reference IDs, making them essentially 14 digit IDs, when all 16 digits are required. For Theta for DG Granule cells, there should be 6 citations, including the new data that I am still working on trying to include. The current Theta DG Granule cell Evidence page only lists 3 citations. However, when you open the citations, I believe the last citation by Mizuseki et al, 2009, is actually a compendium of 3 sets of data, which have somehow been mixed together under the single citation header.

**Comment by drdiek** [comment]
@nmsutton I made a mistake. There are only 5 citations expected for Theta for DG Granule cells. Therefore, all of the data is showing up, just not properly listed under the correct citation headers.

**Comment by drdiek** [comment]
@nmsutton The 5 Theta values that should be listed on the Evidence pages are 40, 124, 75, 116, and -92, with 124 being the preferred value. The preferred value is properly being listed in the main matrix. How did we decide on what to list in the hover-over window? Right now it references only the single preferred value. I was expecting it to list the full range of values from [-92, 124] with 5 measurements.

**Comment by nmsutton** [comment]
@drdiek the main matrix hover-over displays "representative conditions" and "range". In the case you describe the range given the median's representative conditions has a count of 1. Including all values means including multiple representative conditions unless we describe the range differently, such as "range irrespective of representative conditions listed here". Even if we describe it differently I would wonder what confusion there could be for user who have to separate the range values from the representative conditions listed below. Since the evidence page lists all values and matching representative conditions, that is one area that the information is less confusing. I am open to idea about how to display the hover-over, and currently it is displayed in a way that seem to me to cause least user confusion.

**Comment by drdiek** [comment]
@nmsutton I notice that in property_page_phases.php, you create a temporary table wherein referenceID is declared to be BIGint(25). Since the Reference IDs in the phases table are in quotes, will this cause a conflict somehow?

In your php code, when you comment sections in which you are querying the database, it would helpful if you could please explicitly mention the table you are reading from, as it is not always clear to me.

**Comment by drdiek** [comment]
@nmsutton The "Show:" and "Order:" pull down menu selectors on the phases Evidence pages do not work. I would suggest that they be removed if it is too difficult to make them work.

**Comment by nmsutton** [comment]
@drdiek I have removed the selectors for the time being.

**Comment by drdiek** [comment]
@nmsutton I am a little confused by the code in property_page_phases.php because of all of the legacy code. I am having a hard time parsing out the bits that are supposed to work for the phases-related citations.

**Comment by nmsutton** [comment]
@drdiek I fixed one issue with the values matching articles, where an index was off by 1. The corrected Senzai and Buzsaki, 2017 [28132824]: 40. I found the source of the Xiaomin et al., 2020 [32763145]: -92 issue to be a mismatch in the phases_fragment table where pmid 32763145's pmid_isbn_page did not match 1212, which is the value in the hco db's Article table. Once all pmid_isbn_page values are changed to 1212, the "-92" values shows up in the correct article. I looked at the article with 32763145 and the original listed pmid_isbn_page did not appear possible given the 1212–1225 range of pages it spans. Is it fine to change that pmid_isbn_page in phases_fragment?

**Comment by drdiek** [comment]
@nmsutton Good catch. Yes, go ahead and change it.

**Comment by drdiek** [comment]
@nmsutton One last little change, please. When you open the Evidence, after the value, such as for Theta, is listed, it says "Representative selection" and lists the protocol metadata. Since we are listing all values here, they are no longer "representative," they are simply what they are. Can you please change this to read simply "Protocol"?

**Comment by nmsutton** [comment]
@drdiek I have made the requested update. I think the work on this github issue may be completed now but I will read through your earlier comments more to make sure of that.

**Comment by nmsutton** [comment]
@drdiek thanks you for reviewing this work and closing the issue. Just as a follow-up to some of your earlier comments, it appears the RefID inserted into the temp table is from the phases_fragment table, not the phases table, and quotes around RefIDs is not present there, so there does not appear to be an issue with that. Also, I did not hear anything further from you after my earlier description of why the ranges are shown the way they are on the main matrix as compared to the evidence page. Does that mean it is fine to have them displayed that way due to the explanation in my earlier comment?

**Comment by drdiek** [comment]
@nmsutton Perhaps we could add a line to the hover-over window that would be borrowed from the Membrane biophysics hover-over windows: "Representative value selected from <n> sources". If you got really fancy, you could specify "source" vs. "sources" depending on the number of sources, which is what the Membrane biophysics windows do.

**Comment by nmsutton** [comment]
@drdiek ok, if I understand correctly, you want the range to display all values (instead of the ones specific to the representative selection) and the representative selection description to be changed to "representative selection from 1 source" or X sources if it is more than 1 source value? In contrast to the membrane biophysics page, it would not make sense to write "representative value" because the protocol conditions are names not values.

**Comment by drdiek** [comment]
@nmsutton I want to replicate as best as possible the hover-over window for Membrane biophysics. For example, for Rin for DG Granule cells, the representative value being displayed is 228.0. The hover-over window expands on that with the accompanying error and protocol. That value of 228.0 plus its error is based on 31 measurements. However, for Rin for DG Granule cells, the representative value of 228.0 was chosen from a selection of 5 possible source values. For the phases, we should leave the range and Measurements section and Representative selection alone. I simply want to add the total number of sources, for example, for Theta for DG Granule cells there are 5. This is how the Membrane biophysics window works, I believe.

**Comment by nmsutton** [comment]
@drdiek ok, perhaps I understand it now, thanks. As a preview the phases matrix hover-over for theta for DG Granule cells will be:
`Range: [124.00, 124.00]`
`Measurements: 5`
`Representative selection: rats, young adult, male and female, whole-cell patch clamp, head-fixed awake`
`Representative value selected from 1 source`
This is acceptable?
There are not 5 sources used to determine the median value in the main matrix, there was 1. 1 value was ranked lower than the 5 total values that match theta for DG Granule, and that value was used as the source for the median value. I changed the measurements value to match the way the memb. biophy. page refers to it from what it appears (count of all values irrespective of rep. cond.). Having the range being 1 value used to find the median, and the measurements being 5 listed directly after that might be confusing for users as seen in the example above.

**Comment by drdiek** [comment]
@nmsutton Perhaps we can move the Measurements line to the last and modify it to read something like "Total measurements".

**Comment by nmsutton** [comment]
@drdiek sounds good, I will program it that way.

**Comment by nmsutton** [comment]
@drdiek I have now added the new design for the main matrix hover-overs. Please review it and tell me if it looks acceptable.

**Comment by drdiek** [comment]
@nmsutton They look good.
