### ISSUE TITLE
DWW: [phases] Add "dentate spike ratio" to the possibilities for the "Other" column in the main matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#578]
The dentate spike ratio should be ranked just ahead of the run/stop ratio.

**Comment by nmsutton** [comment]
@drdiek In my meeting with Giorgio yesterday, he said he is interested in showing a number in the other column that represents the count of relevant other column entries. Please help me understand, how specifically should this be shown in the matrix (including the hover-over)?

**Comment by drdiek** [comment]
@nmsutton I am currently working on adding the new data to the spreadsheet and to the database. I will soon write up a description of what exactly needs to be done with this new data.

**Comment by nmsutton** [comment]
@drdiek I never added "dentate spike ratio" to the rankings because this issue was closed. Is it no longer wanted for me to add that?

**Comment by drdiek** [comment]
@nmsutton Sorry, I do not remember why exactly I had decided to close this issue.

**Comment by nmsutton** [comment]
@drdiek this has been added. Please review the work to see if it is completed.
