### ISSUE TITLE
DWW: [phases] Columns to appear in the new expanded main matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#580]
@nmsutton Here are the columns that should appear in the expanded matrix, when the toggle is set, with the order ranking listed in square brackets:

DS ratio [1]
Ripple (deg) [2]
Gamma (deg) [3]
Run/stop ratio [4]
Epsilon [5]
Vrest (mV) [6]
Tau (ms) [7]
APthresh (mV) [8]
fAHP (mV) [9]
APpeak-trough (ms) [10]

**Comment by nmsutton** [comment]
@drdiek I think I may have this working on devur2 now but I want to review the value calculations more. There is now a checkbox for "All Other Values" at the top of the page that activates the display of the additional columns. Each additional column is designed to display values the same way as the other columns, where the median of the lowest ranked values are reported along with the hover-over that describes the experimental conditions that match that rank.

**Comment by drdiek** [comment]
@nmsutton Can you please move the new checkbox far over to the right. Right now it is very hard to see.

**Comment by nmsutton** [comment]
@drdiek I have moved the checkbox.

**Comment by nmsutton** [comment]
@drdiek given all the ranking listed here, should the unexpanded single other value be based on all of these columns or the more limited selection of them?

**Comment by drdiek** [comment]
@nmsutton It would be most favorable to have a value listed in the unexpanded single other column for each neuron type, if at all possible, so I would base the value on all possible alternatives.

**Comment by nmsutton** [comment]
@drdiek ok, when you write "all possible alternatives" I assume that means the 10 columns listed above.

**Comment by drdiek** [comment]
@nmsutton Yes, that is what I mean.

**Comment by nmsutton** [comment]
@drdiek at my meeting with Giorgio today I mentioned some next work I will do is adding the number value to the unexpanded other column and he suggested a different approach. He referenced a description from a prior email he sent on Nov. 14 where he recommended " “& x other” after the top choice if x>0 (say, “gamma and 3 other”) ". He said that he anticipates other values in the unexpanded other column would be confusing to users. Please share, it is fine if we do this the way he described?

**Comment by drdiek** [comment]
@nmsutton Yes, let's proceed with his recommendation.

**Comment by nmsutton** [comment]
@drdiek I have added the requested work. Please review this to see if it is completed. One note is that the new content descriptions are also in the neuron page display, and the same code is used in the retrieval of values in the evidence pages, so in your review all of those things should be working correctly.
