### ISSUE TITLE
DWW: [phases]: Make the "All Other Values" selector more obvious

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#587]
Reviewer #3: "First, I was unable to locate some of the new data from the current manuscript on Hippocampome.org. In particular, it seems to me that the data on in vivo membrane properties (presented in Table 1 of the paper) has not been added to the appropriate part of Hippocampome.org."

@drdiek: The values are already in the database and available in the expanded matrix. Therefore, I think the solution is to try to make the selector used to expand the matrix much more obvious. I would start by moving the "All Other Values" selector farther to the right to clearly separate it from the metadata selectors. We might also try to highlight it in some way by increasing the font size, emboldening the font, or drawing a box around the selector and label.

**Comment by nmsutton** [comment]
@drdiek I moved the checkbox to the right somewhat, added a border, and increased the font size. Please tell me if it looks acceptable.
