### ISSUE TITLE
DWW: [phases]: The metadata filters do not properly filter out data when no metadata are selected

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#589]
Reviewer #3: "Third, the ability to filter data points according to a variety of factors is a great new feature which considerably enhances the usability of the database, especially given the substantial differences that are sometimes observed between experimental conditions. However, this feature does not currently seem to work as expected. For example, if I select a combination of factors (conditions) for which there are currently no data available (or if I simply deselect all factors) and press the "update" button, the table gets updated, but there are still values shown in every cell of the table (except in a few that are always empty) - although when I hover the cursor over these entries, the system (correctly) shows the number of relevant sources and measurements as 0."

**Comment by nmsutton** [comment]
@drdiek I think I have perhaps fixed this issue. Please test the current version of the phases page and see if this appears completed.

**Comment by drdiek** [comment]
@nmsutton It looks good to me.
