### ISSUE TITLE
DWW: [phases]: Distinguish subtypes from generic types in the phases matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#593]
Reviewer #3: “In addition, a way should be found to include and clearly display data that are specifically about the newly created subtypes, but also data which are associated with the more general cell type (i.e., where the subtype is unknown).”

@drdiek: "I take this to mean that we need some way to display information for generic CA1 Pyramidal cells that is separate from that for CA1 Superficial and Deep Pyramidal cells. How should we tackle this? We could always have 3 cell types, 1 generic and 2 specific, where we color the rows of the subtypes a different color, possibly, to distinguish them from the generic type. Or, we could possibly include all three types and just indent the Superficial and Deep types’ names in order to indicate that they are subtypes."

Giorgio: "I haven’t formulated a cognizant opinion on this yet, but I would view the indentation and differential color-coding of the subtypes as mutually reinforcing (AND) rather than alternative (OR)."

**Comment by drdiek** [comment]
@nmsutton I have been creating a generic CA1 Pyramidal cell entry vs. subtype CA1 Superficial and Deep Pyramidal cell entries for the morphology, membrane biophysics, and connectivity matrices. I am now trying to do the same for the phases matrix; however, I am finding that the code I have implemented for the other matrices is not working for the phases matrix. In particular, I have manipulated the final sections of code in getMorphology.php, getEphys.php, and getConnectivity.php. The final section of getPhases.php does not seem to control the display of the matrix in the same way as the others. Which file should I be looking at for the phases matrix? You can take a look at the other matrices on devur3 to see what I am trying to do.

**Comment by nmsutton** [comment]
@drdiek I have updated the phases matrix to include the additional entries using the same formatting you used on the morphology matrix. The matrix auto recognized values it appears for each type based on the db you have on devur3. A reason the phases matrix is different in the way it stores neuron types is that it dynamically pulls live db data unlike other matrixes (to accommodate all the condition check boxes), therefore the code that needed to be updated was in /phases/gen_json/. Please review this work and see if it looks acceptable. Also if possible see if the values present in the new types on the phases matrix seem appropriate.

**Comment by drdiek** [comment]
@nmsutton The display looks good, and the values, at least for Theta look good, too. However, there is now an problem with the Evidence pages linked to the new variants of CA1 Pyramidal cells. Please refer to Issue #596.
