### ISSUE TITLE
DWW: [phases]: The Evidence pages for the new generic CA1 Pyramidal cells and the CA1 Superficial and Deep Pyramidal cells are not working

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#596]
@nmsutton The Evidence pages are not displaying correctly for the 3 variants of CA1 Pyramidal cells. Sometimes they vanish completely or else they only display a fraction of the entries that they should.

**Comment by nmsutton** [comment]
@drdiek I have updated the phases_evidence_fragment_rel and phases_evidence_type_rel tables to reflect the changes you made to phases_fragment for the new types. The evidence pages appear to me to be correctly displaying entries now. The process of updating the tables is not an automated one, and I didn't know that phases_fragment was updated, so for future reference please inform me of such changes to make sure I update the connected tables. Please review this work and see if it looks complete.

**Comment by drdiek** [comment]
@nmsutton For me the listing of the Neuron Type names has not changed in the phases matrix, meaning the generic CA1 Pyramidal cell type is missing and the two subtypes are not colored blue and indented. Did you update all of the code in devur2, or am I doing something wrong? I cleared the json file and cleared my browser cache, but the display remains unchanged. I am afraid of doing something to the phases portion of the site, so I have not tried to change any files myself.

**Comment by nmsutton** [comment]
@drdiek I updated devur3 not yet devur2. Since devur2 is the link that was released in the current article, I am waiting for your approval of the content on devur3 before updating devur2.

**Comment by drdiek** [comment]
@nmsutton I am still not seeing the correct entries on the Evidence pages on devur3. For example, for CA1 Superficial Pyramidal cells for Theta, I see only entries from Oliva et al., 2016 [27650887].

**Comment by nmsutton** [comment]
@drdiek I am seeing correct results on my local server and incorrect results on devur3. This indicates to me that potentially the database was overwritten since I last uploaded the version with the correct new tables. Have you uploaded a new database version to devur3 since 2 days ago? If so please use the latest csv2db code because the correct csv files have now been included in it and need to be included in any new build to get the evidence pages working correctly.

**Comment by drdiek** [comment]
@nmsutton Updating csv2db fixed my problems. I notice now that some of the characters in the quotes are not coming through correctly. If I were to correct these characters in phases_fragment.csv, would you need to update any other files?

**Comment by nmsutton** [comment]
@drdiek glad to hear that. I expect that the text in phases_fragment.csv is what will show on the evidence page, so I won't need to update any other files if you correct the characters. Thanks for doing that.
