### ISSUE TITLE
GAA: [phases]: Add a linked jpeg version of Figure 5A from the manuscript to the phases matrix page

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#598]
@nmsutton I have added a new file to the images/ directory called Theta_and_SWR_Ratio.jpg. This file should be linked to the main phases matrix page the same way that there is a jpg version of the connectivity matrix linked to the main connectivity matrix page. The tag line should be "View the Theta and SWR Ratio values as a .jpg image". As far as the link and text placement, I would try to put them under the rightmost portion of the banner's blue stripe, to the right of the "All Other Values" checkbox.

**Comment by nmsutton** [comment]
@drdiek Thanks for adding and updating the image. I added this work on devur3. Please take a look at it and see if this issue is complete.
