### ISSUE TITLE
DWW: [phases]: Determine the N values for all of the phases-related values in the main spreadsheet

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#599]

**Comment by drdiek** [comment]
@nmsutton When I am unable to determine the N for a particular measurement that has an error associated with it, what should I enter? Something along the lines of "NA" or "N/A" or should I just leave it blank?

For those measurements that do not have an associated error associated with them, the assumption is that N = 1. I am trying to enter a "1" anyway, but if I miss an entry, that is the assumption.

**Comment by nmsutton** [comment]
@drdiek I think any of those options would be fine.

**Comment by drdiek** [comment]
@nmsutton OK, I will go with "NA" just so I do not leave anything blank.

**Comment by nmsutton** [comment]
@drdiek just checking in on this, please share, was the update of new data completed here (resolving this issue) or it is still in progress?

**Comment by drdiek** [comment]
@nmsutton I am still working on it. I keep getting sidetracked by more pressing items. To me having the errors appear successfully on the website was more important than getting the N values to appear, which is why I have not super-prioritized the N values.

**Comment by nmsutton** [comment]
@drdiek no problem, thanks for the details.
