### ISSUE TITLE
DWW: [phases] Post to the portal the N values for all phases-related values with errors

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#601]
This Issue is dependent on the completion of Issue #599.

**Comment by drdiek** [comment]
@nmsutton I have finished entering all of the N values, including creating N's for the gamma, epsilon, and ripple values. I have uploaded the updated database to devur3 for testing.

**Comment by nmsutton** [comment]
@drdiek I think I may have this working on devur3. It reports errors and error N except for run_stop_ratio, which from my understanding does not have errors reported for it. Please take a look at this and see if it is working correctly.

**Comment by drdiek** [comment]
@nmsutton Can you please arrange for there to be no listing for N when the value is equal to "NA"? Right now it lists as "1," which is strictly incorrect. The correct N is simply unknown in some circumstances, even though there is an error listed and the N is obviously greater than 1.

**Comment by nmsutton** [comment]
@drdiek I have added the requested update. Please take a look and see if it looks correct. Some examples are with neuron id 1000 there is a thetaN = 1 with theta = -92.43 and another thetaN = "" with theta = 75.11. On neuron id 4036 there is thetaN = "NA" when theta = 12. All of these appear reported as wanted now.
