### ISSUE TITLE
DWW: [phases] Add new DG neuron type to the main phases matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#603]
@nmsutton At the request of Reviewer #2, I have added some new data from a reference article that they suggested. This has resulted in the addition of 3 GABAergic (red font) DG neuron types to the phases matrix, which will appear in this order right after Mossy:

DG Basket [1035]: SWR ratio, DS ratio
MOPP [1008]: SWR ratio
Total Molecular Layer [1004]: SWR ratio, DS ratio

Can you please make the necessary modifications to make these new neuron types appear in the phases matrix?

**Comment by nmsutton** [comment]
@drdiek I updated the neurons on the main matrix. I also updated the phases evidence-related tables but found that when I rebuilt the database your 3 new types were not present. Therefore evidence page data for them is missing. Can you please update the relevant phases tables in csv2db with your 3 new neuron types so that rebuilding the db includes them?

**Comment by drdiek** [comment]
@nmsutton Sorry about that. I forgot to update GitHub, but have done so now.

**Comment by nmsutton** [comment]
@drdiek I have rebuilt the database and the evidence for the new types is now showing up. I had to add the new article to the Article table. Please review if this work is completed.

**Comment by drdiek** [comment]
@nmsutton It looks good.

**Comment by drdiek** [comment]
@nmsutton I appear to have done something inadvertent again. The Evidence for the new DG neuron types is not showing up.

**Comment by nmsutton** [comment]
@drdiek from your latest csv2db update, the only thing that seems like it would have affected this is your article.csv changes. Please check that compared to the article.csv version before your update to see if it is causing the missing evidence article.

**Comment by drdiek** [comment]
@nmsutton The Evidence page is not completely blank, as it has been during previous failures. It actually lists the following message: "There are no results available." This would suggest that the query to the database that enumerates the number of citations is not returning anything. Does this suggest anything to you?

**Comment by drdiek** [comment]
@nmsutton Other newer articles added to article.csv are showing up, so I do not think that is the source of the problem.

**Comment by drdiek** [comment]
@nmsutton I solved the problem. I use a local directory called csv2db_import_Diek to run my tests before I copy files over to csv2db_import for storage on GitHub. I had neglected to update my versions of phases_evidence_type_rel.csv and phases_evidence_fragment_rel.csv, which you had updated last week.
