### ISSUE TITLE
KM: [synaptic physiology] Create tools page

### ISSUE THREAD

**Issue by nmsutton** [Hippocampome-Org/php#610]
We should create a tools page to be located at hippocampome.org/php/tools.php and reached by hippocampome.org/tools/. Kievan, can you please attach a mockup of the page in docx/pdf/pptx format here and we will convert it to HTML? If you want you can write in HTML but that is not required.

**Comment by k1moradi** [comment]
On second thought, I think using hippocampome.org/tools/ just for synaptic modeling tools might not be fair. Maybe hippocampome.org/SynapseModelingTools is a better name. 

I am thinking of making a landing page for all synapse modeling tools that has three sections. One for Synapse Modeling Utility, one for the simulation in NEURON software, and one for the machine learning library. In the future, we can add a fourth section that includes the junction potential and reversal potential calculator.

[Also, all new hard links of my paper should point to the review site (hippocampome.org/phprev) for the time being, until the final approval for the publication.]

**Comment by drdiek** [comment]
@k1moradi We could just make an all-encompassing Tools page that has Carolina's tool in one section and all of your tools, in all of their subsections, in another.

**Comment by drdiek** [comment]
@nmsutton and @k1moradi Here is a quick mockup of a potential Hippocampome.org Tools page.

[Hippocampome.org Tools.docx](https://github.com/Hippocampome-Org/php/files/6030161/Hippocampome.org.Tools.docx)

**Comment by k1moradi** [comment]
My edits to the suggested mockup. 

[Hippocampome.org.Tools.docx](https://github.com/Hippocampome-Org/php/files/6030532/Hippocampome.org.Tools.docx)

Should we add Giorgio to this discussion?

**Comment by drdiek** [comment]
@nmsutton The modifications to httpd.conf should be directed to phpdev, where the latest working version of Keivan's interactive matrix is currently found. We can re-edit the file later to point to php after his manuscript is accepted for publication.

@k1moradi Before we re-involve Giorgio, to what exactly are we linking the final sub-section? Have you created the machine learning library yet?

**Comment by k1moradi** [comment]
My project is complete, so yes, we have a machine learning library now.

**Comment by nmsutton** [comment]
@drdiek @k1moradi Links have now been updated.

**Comment by k1moradi** [comment]
Nate could you successfully go to the landing page. The redirection works but I redirected to the "php" site, but not the "phprev", or "phpdev".

**Comment by nmsutton** [comment]
@k1moradi yes, I was able to. Please clear your cache or restart your browser window.

**Comment by k1moradi** [comment]
OK thanks

**Comment by drdiek** [comment]
@k1moradi What is the link address to your machine learning library?

**Comment by nmsutton** [comment]
@drdiek @k1moradi I have now created the tools page. Some of the links were not yet shared, so when they are available, please post them here and I will add them to the page. I made the page style similar to the help page. On the main menu clicking the "tools" menu option now brings one to the tools page. I also added some minor grammar edits to the paragraph beginning "The convergence...". I assume those are correct unless I hear otherwise.

**Comment by drdiek** [comment]
@nmsutton Thank you for taking the initiative on this. It looks fine to me. As you say, all that is needed is to add the remaining links.

**Comment by k1moradi** [comment]
Thanks, @nmsutton! I am working on the links. I will post them here soon.

**Comment by nmsutton** [comment]
@drdiek @k1moradi You're welcome. I mentioned work on the tools page today in my meeting with Giorgio and he had some new advice about it. His preference would be for the tools page to only contain Keivan's work because he views it may confuse users to have the links for other work on both the drop-down menu and web page. I think there was some misunderstanding about the design wanted but this can be fixed with the advice he gave. He doesn't want the tools menu icon to link to the page. He advised in this case the tools page name and title should be changed. Please tell me, what would be a better new name, "Synapse Physiology Tools", "Synaptome Tools", "Synaptic Modeling Tools", or something else?

**Comment by k1moradi** [comment]
"Synapse Modeling Tools"

**Comment by nmsutton** [comment]
@k1moradi thanks. Also, please tell me, would you like hippocampome.org/SynapseModelingTools, hippocampome.org/tools, or both of these to link to the Synapse Modeling Tools page?

**Comment by k1moradi** [comment]
@nmsutton hippocampome.org/SynapseModelingTools sounds good.

**Comment by nmsutton** [comment]
@k1moradi @drdiek I have now updated the Synapse Modeling Tools (smtools) page. Giorgio requested that the tools menu option for Keivan's work go to the smtools page and therefore I have added that. In the tools menu drop down "Synapse Modeling" now goes to the tools page. The link hippocampome.org/SynapseModelingTools goes there now also. Giorgio did not want clicking the tools menu icon to go anywhere, and I have now make it act that way. Originally the "Synapse Modelers" tools menu option went to a master.zip file, and I have moved that to one of the links in the smtools page. @k1moradi can comment on if that looks the way that is wanted.

**Comment by k1moradi** [comment]
@nmsutton the page and links look good for now. I'm still working on the ML library page and let you know whenever it was ready.

**Comment by k1moradi** [comment]
@nmsutton I made the machine learning library page on GitHub. Could you please update the synapse modeling page?

https://github.com/k1moradi/MachineLearningSynapsePhysiology

**Comment by nmsutton** [comment]
@k1moradi nice work. It is now updated.

**Comment by k1moradi** [comment]
Thanks :)
