### ISSUE TITLE
LMP: [Synaptic Physiology] The Synaptic Physiology matrix is not showing up

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#619]
LMP: "The Synaptic Physiology matrix is not uploading properly, at least in our browsers"

@nmsutton I believe we need to back track here to just the previous instructional web page, since the working version of the Synaptic Physiology matrix is on dev.

**Comment by nmsutton** [comment]
@drdiek thanks for the advice, I have now updated this.
