### ISSUE TITLE
DWW: [counters] The Hits and Unique Hits counters are displaying zero hits

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#637]

**Comment by nmsutton** [comment]
@drdiek thanks for looking into this. I use this code for counters: https://defuse.ca/php-hit-counter.htm
It appears to me someone deleted the "counters_db_id table from the hippocampome database, and that is a needed table.
```
mysql> select * from counters_db_id;
ERROR 1146 (42S02): Table 'hippocampome.counters_db_id' doesn't exist
```
Here is a create statement for it:
```
CREATE TABLE `counters_db_id` (
  `database_id` int NOT NULL,
  PRIMARY KEY (`database_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
For the *hippocampome* database, it should have a single row with a value of 1 in the database_id column
This is done by
```
mysql> INSERT INTO `hippocampome`.`counters_db_id` (`database_id`) VALUES ('1');
```
I recreated this and the counters are back working. Please update any database copies you have with this to avoid this getting lost in the future. Also, *importantly* the databases are numbered as follows:

hippocampome: 1

hippodevome: 2

hipporevome: 3

hippocsv2db: 4

Please have the database_id values match that for each appropriate database.

Additional database_id numbers can be added for other database versions if wanted.

The hits counters now use the "counters" database on the cng servers. I checked today and found:
```
mysql> select * from campome_hits;
+--------+----------+----------+
| pageid | isunique | hitcount |
+--------+----------+----------+
| 1      |        1 |    18910 |
| 1      |        0 |    91540 |
+--------+----------+----------+
```
It looks like the hits are recorded in the database but was not displaying on the site.

**Comment by nmsutton** [comment]
@drdiek I checked the csv2db_import repo and I'm not sure how the counters_db_id tables were added in the past but I created a new insert_hit_counter_ids.sql script and added a line to import it into example_database_save.sh. Perhaps there was not an automated process to add the table in the past so it was getting lost and no one accidentally deleted it. Please update any database_save.sh scripts you have (or any alternative scripts you use) in association with csv2db_import and the database should now automatically build with the needed counters_db_id tables.
