### ISSUE TITLE
GAA: [search]: Adjust the search results listings to include both unknown and positive hits for markers searches for v2.0

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#669]
When doing a compound search for CB1 and VIP, there are no neuron types that are positive for both markers. The search results currently return a listing of all neuron types that are unknown for both markers. The results should be modified to also include listings of neuron types that are positive for one marker and unknown for the other.

**Comment by knadellaCH** [comment]
[Week 3 Status.docx](https://github.com/Hippocampome-Org/php/files/9634556/Week.3.Status.docx)

**Comment by drdiek** [comment]
This Issue has been superseded by Issue #712.
