### ISSUE TITLE
KM: [tools]: Add a tools page for the Reversal potential and Junction potential calculator

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#682]
@k1moradi: For 2.0, I wished we could have a tools page for Reversal potential and Junction potential calculator. I know HBP is using it. Right now the calculator is deep in a Google sheet, which is hard to access.

**Comment by k1moradi** [comment]
We already had an open issue for this. Nikhil worked on it a bit, but I'm not sure what happened at the end.

**Comment by drdiek** [comment]
@k1moradi OK, I found the old issues. I see that you even posted some Javascript code for your calculations. I am not sure how, but it seems like we should be able to make this happen. If I am not able to puzzle it out, then perhaps we will be able to tap Nate (@nmsutton) sometime when he is not so busy.
