### ISSUE TITLE
Simulate script not functioning properly 

### ISSUE THREAD

**Issue by sivaven** [Hippocampome-Org/php#733]
I tried several neuron types. The simulate feature is not reproducing the actual dynamics. I wonder if this change caused this. 
https://github.com/Hippocampome-Org/php/commit/9386926b9fe08af0f7542917898a530a85b027a8
![Screenshot 2023-03-13 104645](https://user-images.githubusercontent.com/2738449/224737250-becf7837-9d09-44c5-9485-5c65bf6d992a.png)

**Comment by sivaven** [comment]
Attached is an example from neuron type 4012. It should reproduce a PSTUT pattern for the given current.

**Comment by drdiek** [comment]
A toggle has now been implemented that will activate the refractory period. When the toggle is active, a warning message appears notifying the user that the refractory period was not a part of the original Izhikevich model formulation.
